<div class="s-header-2">
    <div class="s_top">
    	<?php if($this->newsHot) { ?>
	        <div class="container">
	    		<div class="b-sslide-default">
				    <div class="slick-slider">
				    	<?php foreach ($this->newsHot as $value) {
				    		echo '<a href="'.PUBLIC_PATH.$value['slug'].'">'.$value['name'].'</a>';
				    	} ?>
				    </div>
				</div>
	        </div>
	    <?php } ?>
    </div>
    <div class="s_bot">
        <div class="container align-items">
            <a href="<?php echo PUBLIC_PATH; ?>" class="align-items hd-logo">
                <img loading="lazy" width="400" height="300" src="<?php echo PUBLIC_PATH.UPLOAD_IMAGES.date('Y/m',explode('-',$this->info['logo'])[0]).'/100x76-'.$this->info['logo'].WEBP_EXT; ?>" alt="<?php echo $this->info['name']; ?>">
            </a>
            <div class="hd-menu">
                <a href="javascript:;" ht-trigger="hd-menu"><i class="fa fa-bars" aria-hidden="true"></i></a>
                <ul ht-target="hd-menu">
                	<?php foreach ($this->menu as $value) { ?>
                		<li>
	                    	<a href="<?php echo $value['id'] == 121 ? $value['multi_input']['link'] : PUBLIC_PATH.end(explode(',',$value['link'])); ?>" <?php echo $value['id'] == 121 ? 'target="_blank" rel="nofollow"':''; ?>><img loading="lazy" width="400" height="300" src="<?php echo PUBLIC_PATH.UPLOAD_IMAGES.date('Y/m',explode('-',$value['multi_image']['icon'][0]['thumbnail'])[0]).'/100x100-'.$value['multi_image']['icon'][0]['thumbnail'].WEBP_EXT; ?>" alt="<?php echo $value['name']; ?>"><div><?php echo $value['name']; ?></div></a>
	                    	<?php if($value['child']) { ?>
		                    	<div class="hd-sub">
		                            <div class="row row-flex">
		                            	<?php foreach ($value['child'] as $child) {
		                            		echo '<div class="col-md-3"><h2 class="hd-title"><a href="'.PUBLIC_PATH.(preg_replace('/(-[0-9]+-[0-9]+\.html)$/', '', $child['link'])).'">'.$child['name'].'</a></h2>';
		                                    if($child['child']) {
			                                    echo '<ul>';
			                                    foreach ($child['child'] as $item) {
                                                    if($value['id'] == 23) {
    			                                    	echo '<li><a href="'.PUBLIC_PATH.(preg_replace('/(-[0-9]+-[0-9]+\.html)$/', '', $child['link'])).'-'.(preg_replace('/(-[0-9]+-[0-9]+\.html)$/', '', $item['link'])).'">'.$item['name'].'</a></li>';
                                                    } else {
                                                        echo '<li><a href="'.PUBLIC_PATH.(preg_replace('/(-[0-9]+-[0-9]+\.html)$/', '', $item['link'])).'">'.$item['name'].'</a></li>';
                                                    }
			                                    }
			                                    echo '</ul>';
			                                }
			                                echo '</div>';
		                            	} ?>
		                            </div>
                                    <div class="row">
                                        <div class="col-md-3">
                                            <div class="hd-title"><?php echo $this->info['headline']['slug-2']; ?></div>
                                            <div class="hd-social">
                                                <?php
                                                    echo $this->info['multi_input']['facebook'] ? '<a href="'.$this->info['multi_input']['facebook'].'" target="_blank" rel="nofollow" class="c-icon">
                                                        <img loading="lazy" width="40" height="40" src="'.PUBLIC_PATH.'images/icons/facebook.jpg" alt="facebook">
                                                    </a>':'';
                                                    echo $this->info['multi_input']['youtube'] ? '<a href="'.$this->info['multi_input']['youtube'].'" target="_blank" rel="nofollow" class="c-icon">
                                                        <img loading="lazy" width="40" height="40" src="'.PUBLIC_PATH.'images/icons/youtube.jpg" alt="youtube">
                                                    </a>':'';
                                                    echo $this->info['multi_input']['instagram'] ? '<a href="'.$this->info['multi_input']['instagram'].'" target="_blank" rel="nofollow" class="c-icon">
                                                        <img loading="lazy" width="40" height="40" src="'.PUBLIC_PATH.'images/icons/instagram.jpg" alt="instagram">
                                                    </a>':'';
                                                    echo $this->info['multi_input']['tiktok'] ? '<a href="'.$this->info['multi_input']['tiktok'].'" target="_blank" rel="nofollow" class="c-icon">
                                                        <img loading="lazy" width="40" height="40" src="'.PUBLIC_PATH.'images/icons/tiktok.jpg" alt="tiktok">
                                                    </a>':'';
                                                ?>
                                            </div>
                                        </div>
                                    </div>
		                        </div>
		                    <?php } ?>
	                    </li>
                	<?php } ?>
                </ul>
            </div>
            <div class="hd-menu-2">
                <div class="hd-icon">
                    <?php if($this->logged) { ?>
                        <div class="hd-user">
                            <span class="icon <?php echo $this->logged['thumbnail'] ? 'is-thumb':''; ?>">
                                <?php
                                    if($this->logged['thumbnail']) {
                                        if((file_exists(ROOT_PUBLIC.'/'.UPLOAD_IMAGES.date('Y/m',explode('-',$this->logged['thumbnail'])[0]).'/autox30-'.$this->logged['thumbnail']) && is_file(ROOT_PUBLIC.'/'.UPLOAD_IMAGES.date('Y/m',explode('-',$this->logged['thumbnail'])[0]).'/autox30-'.$this->logged['thumbnail']))) {
                                            echo '<img loading="lazy" width="400" height="300" src="'.PUBLIC_PATH.UPLOAD_IMAGES.date('Y/m',explode('-',$this->logged['thumbnail'])[0]).'/autox30-'.$this->logged['thumbnail'].'" alt="'.$this->logged['fullname'].'">';
                                        } else {
                                            echo '<img loading="lazy" width="400" height="300" src="'.PUBLIC_PATH.'images/noimage.png" alt="'.$this->logged['fullname'].'">';
                                        }
                                    } else {
                                        echo '<i class="fa fa-user-circle-o" aria-hidden="true"></i>';
                                    }
                                ?>
                            </span>
                            <a href="javascript:;">
                                <span><?php echo $this->logged['fullname']; ?></span>
                            </a>
                            <ul>
                                <li class="info">
                                    <a href="javascript:;">
                                        <i class="fa fa-user" aria-hidden="true"></i>
                                        <span><?php echo $this->logged['fullname']; ?></span>
                                    </a>
                                </li>
                                <li><a href="<?php echo PUBLIC_PATH.'profile-71.html'; ?>"><i class="fa fa-info-circle" aria-hidden="true"></i><span>Thông tin cá nhân</span></a></li>
                                <li><a href="<?php echo PUBLIC_PATH.'danh-sach-don-hang-63.html'; ?>"><i class="fa fa-shopping-basket" aria-hidden="true"></i></i><span>Thông tin đơn hàng</span></a></li>
                                <li><a href="<?php echo PUBLIC_PATH.'dang-xuat-74.html'; ?>"><i class="fa fa-sign-out" aria-hidden="true"></i><span>Đăng xuất</span></a></li>
                            </ul>
                        </div>
                    <?php } else { echo '<a href="javascript:;" ht-trigger="c-modal" ht-target="#s-sign-in-1" class="logon"><i class="fa fa-user-o" aria-hidden="true"></i></a>'; } ?>
                    <?php echo $this->info['multi_input']['map'] ? '<a target="_blank" rel="nofollow" href="'.$this->info['multi_input']['map'].'"><i class="fa fa-map-marker" aria-hidden="true"></i></a>':''; ?>
                </div>
                <a href="javascript:;" onclick="window.location.href='<?php echo PUBLIC_PATH.$this->translate("gio-hang-61.html"); ?>';" class="hd-cart">
                    <i class="fa fa-shopping-bag" aria-hidden="true"></i>
                    <span class="bage" ht-cart="bage"><?php echo $this->numCart; ?></span>
                </a>
            </div>
            <div class="hd-search desktop <?php echo $this->logged ? 'logged':''; ?>">
                <a href="javascript:;" class="c-icon-border--primary" ht-trigger="hd-search">
                    <i class="fa fa-search fa-transformation" aria-hidden="true"></i>
                </a>
                <form class="b-search-2" action="<?php echo PUBLIC_PATH.$this->translate('ket-qua-tim-kiem-99.html'); ?>" method="GET" accept-charset="utf-8">
                    <input type="text" name="keysearch" placeholder="Bạn cần tìm ..." value="<?php echo $this->params['query_string']; ?>">
                    <div class="align-items">
                        <span>Sản phẩm</span>
                        <ul style="display: none;">
                            <li <?php echo !$_GET['type'] || $_GET['type'] == 'product' ? ' class="is-focus"':''; ?>><label><input type="radio" name="type" value="product" <?php echo !$_GET['type'] || $_GET['type'] == 'product' ? 'checked':''; ?>><span>Sản phẩm</span></label></li>
                            <li <?php echo $_GET['type'] == 'blog' ? ' class="is-focus"':''; ?>><label><input type="radio" name="type" value="blog" <?php echo $_GET['type'] == 'blog' ? 'checked':''; ?>><span>Blog</span></label></li>
                        </ul>
                    </div>
                    <button type="submit" class="c-btn--primary"><i class="fa fa-search" aria-hidden="true"></i></button>
                </form>
            </div>
        </div>
        <div class="container">
            <div class="hd-search mobile">
                <a href="javascript:;" class="c-icon-border--primary" ht-trigger="hd-search">
                    <i class="fa fa-search fa-transformation" aria-hidden="true"></i>
                </a>
                <form class="b-search-2" action="<?php echo PUBLIC_PATH.$this->translate('ket-qua-tim-kiem-99.html'); ?>" method="GET" accept-charset="utf-8">
                    <input type="text" name="keysearch" placeholder="Bạn cần tìm ..." value="<?php echo $this->params['query_string']; ?>">
                    <div class="align-items">
                        <span>Sản phẩm</span>
                        <ul style="display: none;">
                            <li class="is-focus"><label><input type="radio" name="type" value="product" <?php echo !$_GET['type'] || $_GET['type'] == 'product' ? 'checked':''; ?>><span>Sản phẩm</span></label></li>
                            <li><label><input type="radio" name="type" value="blog" <?php echo $_GET['type'] == 'blog' ? 'checked':''; ?>><span>Blog</span></label></li>
                        </ul>
                    </div>
                    <button type="submit" class="c-btn--primary"><i class="fa fa-search" aria-hidden="true"></i></button>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="s-menu-1">
    <div class="s_menu">
        <div class="s_close"><i class="fa fa-times" aria-hidden="true"></i></div>
        <div class="s_overflow">
            <ul class="s_list">
            	<?php foreach ($this->menu as $value) { ?>
            		<li<?php echo $value['child'] ? ' class="sub1"':''; ?>>
	                    <div class="s_top">
	                        <a href="<?php echo $value['id'] == 121 ? $value['multi_input']['link'] : PUBLIC_PATH.end(explode(',',$value['link'])); ?>" <?php echo $value['id'] == 121 ? 'target="_blank" rel="nofollow"':''; ?>><?php echo $value['name']; ?></a>
	                        <?php echo $value['child'] ? '<div class="s_icon"><i class="fa fa-angle-down" aria-hidden="true"></i></div>':''; ?>
	                    </div>
	                    <?php if($value['child']) {
		                    echo '<ul class="sub1">';
	                    	foreach ($value['child'] as $child) {
	                    		echo '<li><div class="s_top_2"><a href="'.PUBLIC_PATH.(preg_replace('/(-[0-9]+-[0-9]+\.html)$/', '', $child['link'])).'">'.$child['name'].'</a>';
	                            if($child['child']) {
		                            echo '<div class="s_icon_2"><i class="fa fa-angle-down" aria-hidden="true"></i></div></div><ul class="sub2">';
	                            	foreach ($child['child'] as $item) {
                                        if($value['id'] == 23) {
    	                            		echo '<li><a href="'.PUBLIC_PATH.(preg_replace('/(-[0-9]+-[0-9]+\.html)$/', '', $child['link'])).'-'.(preg_replace('/(-[0-9]+-[0-9]+\.html)$/', '', $item['link'])).'">'.$item['name'].'</a></li>';
                                        } else {
                                            echo '<li><a href="'.PUBLIC_PATH.(preg_replace('/(-[0-9]+-[0-9]+\.html)$/', '', $item['link'])).'">'.$item['name'].'</a></li>';
                                        }
	                            	}
		                            echo '</ul>';
		                        }
		                        echo '</li>';
	                    	}
		                    echo '</ul>';
		                } ?>
	                </li>
            	<?php } ?>
            </ul>
            <div class="s_social">
            	<?php
            		echo $this->info['multi_input']['facebook'] ? '<a href="'.$this->info['multi_input']['facebook'].'" target="_blank" rel="nofollow" class="c-icon-bg"><i class="fa fa-facebook" aria-hidden="true"></i></a>':'';
            		echo $this->info['multi_input']['youtube'] ? '<a href="'.$this->info['multi_input']['youtube'].'" target="_blank" rel="nofollow" class="c-icon-bg"><i class="fa fa-youtube-play" aria-hidden="true"></i></a>':'';
            		echo $this->info['multi_input']['instagram'] ? '<a href="'.$this->info['multi_input']['instagram'].'" target="_blank" rel="nofollow" class="c-icon-bg"><i class="fa fa-instagram" aria-hidden="true"></i></a>':'';
            		echo $this->info['multi_input']['tiktok'] ? '<a href="'.$this->info['multi_input']['tiktok'].'" target="_blank" rel="nofollow" class="c-icon-bg c-icon-img" style="background-image: url('.PUBLIC_PATH.'images/icons/tiktok-w.png);"></a>':'';
            	?>
            </div>
        </div>
    </div>
</div>
<p style="position: fixed;opacity: 0.001;z-index: -1;height: 100vh;width: 100%;font-size: 100px;color: #fff;"><?php echo $this->info['name']; ?></p>