<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <?php echo $this->headTitle(); ?>
    <link rel="shortcut icon" type="image/vnd.microsoft.icon" href="<?php echo BE_TEMPLATE.'/layouts/layout/img/favicon.png'; ?>" />
    <!--[if lt IE 9]>
    <script src="<?php echo BE_TEMPLATE.'/global/plugins/respond.min.js'; ?>"></script>
    <script src="<?php echo BE_TEMPLATE.'/global/plugins/excanvas.min.js'; ?>"></script>
    <script src="<?php echo BE_TEMPLATE.'/global/plugins/ie8.fix.min.js'; ?>"></script>
    <![endif]-->
    <?php echo $this->headLink()
        // GLOBAL MANDATORY STYLES
        ->appendStylesheet($this->basePath().'/template/backend/fonts/custom-fonts.css')
        ->appendStylesheet($this->basePath().'/template/backend/fonts/font-awesome/css/font-awesome.min.css')
        ->appendStylesheet($this->basePath().'/template/backend/fonts/simple-line-icons/simple-line-icons.min.css')
        ->appendStylesheet(BE_TEMPLATE.'/global/plugins/bootstrap/css/bootstrap.min.css')
        ->appendStylesheet(BE_TEMPLATE.'/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css')
        // components
        ->appendStylesheet(BE_TEMPLATE.'/global/plugins/animate/animate.min.css')
        ->appendStylesheet(BE_TEMPLATE.'/global/plugins/icheck/skins/all.min.css')
        ->appendStylesheet(BE_TEMPLATE.'/global/plugins/bootstrap-editable/bootstrap-editable/css/bootstrap-editable.min.css')
        ->appendStylesheet(BE_TEMPLATE.'/pages/css/profile.min.css')
        ->appendStylesheet(BE_TEMPLATE.'/global/plugins/bootstrap-fileinput/bootstrap-fileinput.min.css')
        ->appendStylesheet(BE_TEMPLATE.'/global/plugins/bootstrap-sweetalert/sweetalert.min.css')
        // datatable
        ->appendStylesheet(BE_TEMPLATE.'/global/plugins/datatables/datatables.min.css')
        ->appendStylesheet(BE_TEMPLATE.'/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.min.css')
        // datepicker
        ->appendStylesheet(BE_TEMPLATE.'/global/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css')
        ->appendStylesheet(BE_TEMPLATE.'/global/plugins/bootstrap-timepicker/css/bootstrap-timepicker.min.css')
        ->appendStylesheet(BE_TEMPLATE.'/global/plugins/bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css')
        // select
        ->appendStylesheet(BE_TEMPLATE.'/global/plugins/select2/css/select2.min.css')
        ->appendStylesheet(BE_TEMPLATE.'/global/plugins/select2/css/select2-bootstrap.min.css')
        ->appendStylesheet(BE_TEMPLATE.'/global/plugins/bootstrap-multiselect/css/bootstrap-multiselect.min.css')
        ->appendStylesheet(BE_TEMPLATE.'/global/plugins/jquery-multi-select/css/multi-select.min.css')
        // tagsinput
        ->appendStylesheet(BE_TEMPLATE.'/global/plugins/bootstrap-tagsinput/bootstrap-tagsinput.min.css')
        ->appendStylesheet(BE_TEMPLATE.'/global/plugins/bootstrap-tagsinput/bootstrap-tagsinput-typeahead.min.css')
        // jstree
        ->appendStylesheet(BE_TEMPLATE.'/global/plugins/jstree/dist/themes/default/style.min.css')
        ->appendStylesheet(BE_TEMPLATE.'/global/plugins/fancybox/source/jquery.fancybox.css')
        // ticket
        ->appendStylesheet(BE_TEMPLATE.'/apps/css/ticket.min.css')
        // THEME GLOBAL STYLES
        ->appendStylesheet(BE_TEMPLATE.'/global/css/components-rounded.min.css')
        ->appendStylesheet(BE_TEMPLATE.'/global/css/plugins.min.css')
        // THEME LAYOUT STYLES
        ->appendStylesheet(BE_TEMPLATE.'/layouts/layout/css/layout.min.css')
        ->appendStylesheet(BE_TEMPLATE.'/layouts/layout/css/themes/darkblue.min.css')
        ->appendStylesheet(BE_TEMPLATE.'/layouts/layout/css/custom.css')
    ?>
    <?php
        $loader = new \Zend\I18n\Translator\Loader\PhpArray();
        $this->headScript()->appendScript(
            'var BE_LANG = \''.BE_LANG.'\';
            var BE_TEMPLATE = \''.BE_TEMPLATE.'\';
            var IS_USER_CODE = \''.(!!$this->identity()->supper).'\';
            var IS_CONFIG_CONFIRM_EXIT = \''.$this->identity()->config['confirmExit'].'\';
            var TRANSLATOR = '.json_encode($loader->load('default',ROOT.'/module/Backend/language/'.BE_LANG.'.php'), JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE).';
            var _HTTranslator = function($messages) {
                if (TRANSLATOR[\'JS_\'+$messages] == undefined) { return $messages; }
                return TRANSLATOR[\'JS_\'+$messages];
            };',
            'text/javascript',
            array('noescape' => true)
        );

        echo $this->headScript()
            // CORE PLUGINS
            ->appendFile(BE_TEMPLATE.'/global/plugins/jquery.min.js')
            ->appendFile(BE_TEMPLATE.'/global/plugins/bootstrap/js/bootstrap.min.js')
            ->appendFile(BE_TEMPLATE.'/global/plugins/js.cookie.min.js')
            ->appendFile(BE_TEMPLATE.'/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js')
            ->appendFile(BE_TEMPLATE.'/global/plugins/jquery.blockui.min.js')
            ->appendFile(BE_TEMPLATE.'/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js')
            // components
            ->appendFile(BE_TEMPLATE.'/global/plugins/jquery-repeater/jquery.repeater.min.js')
            ->appendFile(BE_TEMPLATE.'/global/plugins/bootstrap-fileinput/bootstrap-fileinput.min.js')
            ->appendFile(BE_TEMPLATE.'/global/plugins/jquery-validation/js/jquery.validate.min.js')
            ->appendFile(BE_TEMPLATE.'/global/plugins/bootstrap-sweetalert/sweetalert.min.js')
            // select
            ->appendFile(BE_TEMPLATE.'/global/plugins/bootstrap-select/js/bootstrap-select.min.js')
            ->appendFile(BE_TEMPLATE.'/global/plugins/jquery-multi-select/js/jquery.multi-select.min.js')
            ->appendFile(BE_TEMPLATE.'/global/plugins/bootstrap-multiselect/js/bootstrap-multiselect.min.js')
            ->appendFile(BE_TEMPLATE.'/global/plugins/select2/js/select2.full.min.js')
            ->appendFile(BE_TEMPLATE.'/global/plugins/quicksearch/jquery.quicksearch.min.js')
            // datatable
            ->appendFile(BE_TEMPLATE.'/global/scripts/datatable.min.js')
            ->appendFile(BE_TEMPLATE.'/global/plugins/datatables/datatables.min.js')
            ->appendFile(BE_TEMPLATE.'/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.min.js')
            // editable
            ->appendFile(BE_TEMPLATE.'/global/plugins/moment.min.js')
            ->appendFile(BE_TEMPLATE.'/global/plugins/jquery.mockjax.min.js')
            ->appendFile(BE_TEMPLATE.'/global/plugins/bootstrap-editable/bootstrap-editable/js/bootstrap-editable.min.js')
            // datepicker
            ->appendFile(BE_TEMPLATE.'/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js')
            ->appendFile(BE_TEMPLATE.'/global/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js')
            ->appendFile(BE_TEMPLATE.'/global/plugins/bootstrap-timepicker/js/bootstrap-timepicker.min.js')
            // tagsinput
            ->appendFile(BE_TEMPLATE.'/global/plugins/bootstrap-tagsinput/bootstrap-tagsinput.min.js')
            ->appendFile(BE_TEMPLATE.'/global/plugins/typeahead/handlebars.min.js')
            ->appendFile(BE_TEMPLATE.'/global/plugins/typeahead/typeahead.bundle.min.js')
            // jstree
            ->appendFile(BE_TEMPLATE.'/global/plugins/jstree/dist/jstree.min.js')
            ->appendFile(BE_TEMPLATE.'/global/plugins/fancybox/source/jquery.fancybox.pack.js')
            // ckeditor
            ->appendFile($this->basePath() . '/template/backend/plugins/ckeditor/ckeditor.js')
            // THEME GLOBAL SCRIPTS
            ->appendFile(BE_TEMPLATE.'/global/scripts/app.js')
            // THEME LAYOUT SCRIPTS
            ->appendFile(BE_TEMPLATE.'/layouts/layout/scripts/layout.min.js')
            ->appendFile(BE_TEMPLATE.'/layouts/global/scripts/quick-sidebar.min.js')
            ->appendFile(BE_TEMPLATE.'/layouts/global/scripts/quick-nav.min.js')
            ->appendFile(BE_TEMPLATE.'/layouts/layout/scripts/custom.js')
            ->appendFile(BE_TEMPLATE.'/layouts/layout/scripts/custom-pages.js');
    ?>
</head>
<body class="page-header-fixed page-sidebar-closed-hide-logo page-content-white page-sidebar-fixed">
    <div class="page-wrapper">
        <div class="page-header navbar navbar-fixed-top">
            <div class="page-header-inner ">
                <div class="page-logo">
                    <a href="<?php echo $this->url('admincp'); ?>">
                        <div class="logo-default">
                            <strong>Admin</strong>
                            <span>LTE</span>
                        </div>
                    </a>
                    <div class="menu-toggler sidebar-toggler"><i class="fa fa-arrow-left" aria-hidden="true"></i></div>
                </div>
                <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse"><span></span></a>
                <a href="<?php echo URL; ?>" target="_blank" class="btn blue yellow-stripe" style="margin-top: 8px;"> <?php echo $this->translate("Xem website"); ?> <i class="fa fa-eye" aria-hidden="true"></i></a>
                <span class="label label-danger" style="position: relative;top: 6px;"><?php if ($this->identity()->supper) { echo preg_replace('/(^.*(backend_?|Backend_?))/', '', BACKEND); } ?></span>
                <div class="top-menu">
                    <ul class="nav navbar-nav pull-right">
                        <?php $MenuCodeTb = new Backend\Model\MenuCodeTb(); ?>
                        <?php if ($MenuCodeTb->getItem((array('id' => 30)))['display']) { ?>
                            <li class="dropdown dropdown-language">
                                <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                                    <img alt="" src="<?php echo BE_TEMPLATE.'/global/img/flags/'.BE_LANG.'.png'; ?>">
                                    <span class="langname text-uppercase"> <?php echo BE_LANG; ?> </span>
                                    <i class="fa fa-angle-down"></i>
                                </a>
                                <ul class="dropdown-menu dropdown-menu-default" style="min-width: auto;">
                                    <?php foreach (array('vi' => 'Tiếng Việt','en' => 'Tiếng Anh') as $lang => $name) { ?>
                                        <li>
                                            <a href="<?php echo PUBLIC_PATH.'admin/'.(($lang == BE_LANG_DEFAULT) ? '' : $lang.'/'); ?>"> <img src="<?php echo BE_TEMPLATE.'/global/img/flags/'.$lang.'.png'; ?>"> <?php echo $this->translate($name); ?> </a>
                                        </li>
                                    <?php } ?>
                                </ul>
                            </li>
                        <?php } ?>
                        <li class="dropdown dropdown-user">
                            <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                                <i class="icon-user"></i>
                                <span class="username username-hide-on-mobile"><?php echo $this->identity()->username; ?></span>
                                <i class="fa fa-angle-down"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-menu-default">
                                <?php if ($this->identity()->supper) { ?>
                                    <li><a href="<?php echo $this->url('admincp',array('controller' => 'menu_code_tb','action' => 'list')); ?>"><i class="icon-list"></i>Menu code</a></li>
                                <?php } if ($this->identity()->supper || $this->identity()->seo) { ?>
                                    <li><a href="<?php echo $this->url('admincp',array('controller' => 'admin_tb','action' => 'field','id' => 1,'root_id' => 23)); ?>"><i class="icon-user"></i>Đổi mật khẩu admin</a></li>
                                <?php } else { ?>
                                    <li><a href="<?php echo $this->url('admincp',array('controller' => 'admin_tb','action' => 'field','id' => $this->identity()->id)); ?>"><i class="icon-info"></i><?php echo $this->translate("Cập nhật thông tin"); ?></a></li>
                                    <li><a href="<?php echo $this->url('admincp',array('controller' => 'admin_tb','action' => 'pass','id' => $this->identity()->id)); ?>"><i class="icon-lock"></i><?php echo $this->translate("Thay đổi mật khẩu"); ?></a></li>
                                <?php } ?>
                                <li class="divider"> </li>
                                <li><a href="<?php echo $this->url('admincp',array('controller' => 'login','action' => 'logout')); ?>"><i class="icon-logout"></i><?php echo $this->translate("Đăng xuất"); ?></a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="clearfix"> </div>
        <div class="page-container">
            <div class="page-sidebar-wrapper">
                <?php echo $this->render('sidebar.phtml'); ?>
            </div>
            <div class="page-content-wrapper">
                <?php echo $this->content; ?>
            </div>
        </div>
    </div>
    <div class="backtop">
        <a href="javascript:;" class="ft-backtop" ht-trigger="backtop"><i class="fa fa-angle-up text--primary"></i></a>
    </div>
    <script type="text/javascript" src="<?php echo BE_TEMPLATE.'/layouts/layout/scripts/beforeunload.js'; ?>"></script>
</body>
</html>