<div class="page-content">
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li><a href="<?php echo $this->url('admincp'); ?>"><?php echo $this->translate("Trang chủ"); ?></a><i class="fa fa-circle"></i></li>
            <li><span><?php echo $this->_params['title']; ?></span></li>
        </ul>
        <?php if ($this->identity()->supper) { ?>
            <div class="pull-right">
                <a href="<?php echo $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'codefield','root_id' => $this->_params['root_id'])); ?>" class="btn green"><i class="fa fa-cogs"></i> Cấu hình dữ liệu</a>
            </div>
        <?php } ?>
    </div>
    <div class="portlet box blue margin-bottom-0">
        <div class="portlet-title">
            <div class="caption"><?php echo $this->translate("Danh sách"); ?> </div>
            <div class="actions">
                <?php if ($this->_field['status']) { ?>
                    <a href="javascript:;" class="btn grey-salsa" onclick="_HTChange.status(this, 'check');"><i class="fa fa-exchange"></i> <?php echo $this->translate("Chuyển trạng thái"); ?></a>
                <?php } ?>
                <a href="javascript:;" class="btn red" onclick="_HTDelete.rows('<?php echo $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'delete')); ?>','/root_id=<?php echo $this->_params['root_id']; ?>');"><i class="fa fa-trash-o"></i> <?php echo $this->translate("Xóa nhiều"); ?></a>
            </div>
        </div>
        <div class="portlet-body">
            <div class="ht-filter">
                <form id="form-filter" action="" method="post" accept-charset="utf-8">
                    <?php if ($this->_field['status']) { ?>
                        <div class="ht-filter__status">
                            <div class="input-group input-group-sm select2-bootstrap-prepend">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button" data-select2-open="ht-open-status"><?php echo $this->translate("Trạng thái"); ?></button>
                                </span>
                                <select id="ht-open-status" name="status" class="form-control select2-not-search" onchange="_HTHelper.submit(this);">
                                    <?php
                                        echo '<option value="all">'.$this->translate("Tất cả").'</option>';
                                        foreach ($this->status as $status => $name) {
                                            echo '<option value="'.$status.'" '.(((string) $status === $this->query['status']) ? 'selected' : '').' >'.$name.'</option>';
                                        }
                                    ?>
                                </select>
                            </div>
                        </div>
                    <?php } ?>
                    <div class="ht-filter__date">
                        <div class="input-group input-group-sm">
                            <input type="text" class="form-control text-center date-picker" name="from" value="<?php echo $this->query['from'] ?>" placeholder="<?php echo $this->translate("Ngày bắt đầu"); ?>" autocomplete="off">
                            <span class="input-group-addon"> <?php echo $this->translate("đến"); ?> </span>
                            <input type="text" class="form-control text-center date-picker" name="to" value="<?php echo $this->query['to'] ?>" placeholder="<?php echo $this->translate("Ngày kết thúc"); ?>" autocomplete="off">
                        </div>
                    </div>
                    <button type="submit" class="btn btn-sm blue pull-right"><i class="fa fa-filter" aria-hidden="true"></i> <?php echo $this->translate("Lọc"); ?></button>
                </form>
            </div>
            <table id="datatable-comment" class="table table-striped table-bordered table-hover table-checkable action-column">
                <thead>
                    <tr>
                        <th class="nosort noexcel table-checkall"><label class="mt-checkbox mt-checkbox-outline"><input type="checkbox" class="group-checkable" data-set=".ht-checkall-rows" /><span></span></label></th>
                        <?php
                            foreach ($this->headers as $header) {
                                if ($header['display'] && $header['colvis'] != true) {
                                    echo '<th class="'.$header['class'].'">'.$header['title'].'</th>';
                                }
                            }
                            if ($this->_field['status']) {
                                echo '<th class="table-show min-width-100">'.$this->translate("Trạng thái").'</th>';
                            }
                        ?>
                        <th class="nosort nosearch noexcel table-func"><?php echo $this->translate("Chức năng"); ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->list as $value) { ?>
                        <?php
                            $linkChange = $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'change','id' => $value['id']));
                            $linkView = $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'view','id' => $value['id'],'root_id' => $this->_params['root_id']));
                            $linkDelete = $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'delete','id' => $value['id']));
                        ?>
                        <tr id="<?php echo $value['id']; ?>">
                            <td><label class="mt-checkbox mt-checkbox-outline"><input type="checkbox" class="ht-checkall-rows" value="<?php echo $value['id']; ?>" /><span></span></label></td>
                            <?php
                                foreach ($this->headers as $header) {
                                    if ($header['display'] && $header['colvis'] != true) {
                                        $val = $value[$header['name']];
                                        switch ($header['name']) {
                                            case 'date_created':
                                                echo '<td class="' . $header['class'] . '">' . date('d/m/Y H:i', strtotime($val)) . '</td>';
                                                break;
                                            case 'comment':
                                                echo '<td class="' . $header['class'] . '"><div>' . $val . '</div></td>';
                                                break;
                                            default:
                                                echo '<td class="' . $header['class'] . '">' . $val . '</td>';
                                                break;
                                        }
                                    }
                                }
                                if ($this->_field['status']) {
                                    echo '<td class="text-center min-width-100">'.$this->status[$value['status']].'</td>';
                                }
                            ?>
                            <td class="table-func">
                                <div class="text-center">
                                    <div class="btn-group btn-group-sm btn-group-solid">
                                        <a href="<?php echo $linkView; ?>" class="btn blue"><?php echo $this->translate("Xem"); ?></a>
                                        <a href="javascript:;" class="btn red" onclick="_HTDelete.item('<?php echo $linkDelete; ?>');"><?php echo $this->translate("Xóa"); ?></a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
    <?php if ($this->_field['status']) { ?>
        <div id="change-status" class="modal fade" tabindex="-1" role="basic" data-backdrop="static" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header"><h4 class="modal-title text-center text-uppercase"><?php echo $this->translate("Chuyển trạng thái"); ?></h4></div>
                    <div class="modal-body">
                        <div class="input-group select2-bootstrap-prepend">
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="button" data-select2-open="ht-open-changeStatus"><?php echo $this->translate("Trạng thái"); ?></button>
                            </span>
                            <select id="ht-open-changeStatus" name="status" class="form-control select2-not-search">
                                <option></option>
                                <?php foreach ($this->status as $status => $name) { ?>
                                    <option value="<?php echo $status; ?>"><?php echo $name; ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <div class="text-center">
                            <button type="button" class="btn salsa" onclick="_HTChange.status(this, 'multi', <?php echo htmlspecialchars(json_encode(array('url' => $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'change'))),JSON_UNESCAPED_SLASHES)); ?>);"><i class="fa fa-exchange"></i> <?php echo $this->translate("Chuyển trạng thái"); ?></button>
                            <button type="button" class="btn red" data-dismiss="modal"><i class="fa fa-ban"></i> <?php echo $this->translate("Hủy"); ?></button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php } ?>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        var tableId = '#datatable-comment';
        var allHeaders = <?php echo json_encode($this->headers); ?>;
        var rows = <?php echo json_encode($this->list); ?>;
        var linkSettingColumns = '<?php echo $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'setting-columns','root_id' => $this->_params['root_id'])); ?>';

        TableDatatables.init({
            tableId: tableId,
            buttons: [
                {
                    className: 'btn grey-salsa',
                    text: 'Tùy chỉnh cột',
                    action: function ( e, dt, button, config ) {
                        window.location = linkSettingColumns;
                    }
                },
            ],
        });
    });
</script>