<div class="page-container-bg-solid">
    <div class="page-content">
        <div class="page-bar">
            <ul class="page-breadcrumb">
                <li><a href="<?php echo $this->url('admincp'); ?>"><?php echo $this->translate("Trang chủ"); ?></a><i class="fa fa-circle"></i></li>
                <li><a href="<?php echo $this->linkList; ?>"><?php echo explode('/', $this->_params['title'])[0]; ?></a><i class="fa fa-circle"></i></li>
                <li><span><?php echo explode('/', $this->_params['title'])[1]; ?></span></li>
            </ul>
            <div class="pull-right">
                <?php if ($this->discount['menu']['define']['order_id'] && !$this->discount['list']) { ?>
                    <a href="<?php echo $this->url('admincp',array('controller' => 'product_discount_tb','action' => 'field','root_id' => $this->discount['menu']['id']), array('query' => array_filter(array('order_id' => $this->_params['id'], 'status' => 1), 'strlen'))); ?>" class="btn green"><i class="fa fa-plus-square-o"></i> <?php echo $this->translate("Tạo mã giảm giá"); ?></a>
                <?php } ?>
                <?php if ($this->item['status'] == 0) { ?>
                    <a href="javascript:;" class="btn blue" onclick="_HTTemplate.yesno('<?php echo $this->translate("Bạn có chắc muốn duyệt đơn hàng"); ?> <strong>#<?php echo $this->_params['id']; ?></strong> ?', '_HTChange.status(this, \'button\', <?php echo str_replace('"', "\'", json_encode(array('url' => $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'change','id' => $this->_params['id'])), 'redirect' => $this->linkList,'status' => 1), JSON_UNESCAPED_SLASHES)); ?>)');"><i class="fa fa-check-square-o"></i> <?php echo $this->translate("Duyệt"); ?></a>
                <?php } ?>
                <a href="<?php echo $this->linkList; ?>" class="btn red"><i class="fa fa-share"></i> <?php echo $this->translate("Thoát"); ?></a>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 memberInfo">
                <div class="portlet mt-element-ribbon light portlet-fit bordered">
                    <div class="ribbon ribbon-left ribbon-clip ribbon-shadow ribbon-border-dash-hor ribbon-color-success uppercase"><div class="ribbon-sub ribbon-clip ribbon-left"></div> <?php echo $this->translate("Thông tin đặt hàng"); ?></div>
                    <div class="portlet-title">
                        <div class="caption caption-profile">
                            <span class="caption-subject font-green bold uppercase"><?php echo $this->item['fullname']; ?></span>
                        </div>
                    </div>
                    <div class="portlet-userpic">
                        <ul class="nav">
                            <?php
                                if ($this->item['address'])  {
                                    echo '<li><span><i class="fa fa-home" aria-hidden="true"></i> ' . $this->item['address'] . '</span></li>';
                                }
                                if ($this->item['phone'])  {
                                    echo '<li><span><i class="fa fa-phone" aria-hidden="true"></i> ' . $this->item['phone'] . '</span></li>';
                                }
                                if ($this->item['email'])  {
                                    echo '<li><span><i class="fa fa-envelope" aria-hidden="true"></i> ' . $this->item['email'] . '</span></li>';
                                }
                            ?>
                            <!-- <li><span><i class="fa fa-info-circle" aria-hidden="true"></i> <?php echo ($this->item['active'] == 0) ? 'Chưa kích hoạt' : 'Đã kích hoạt'; ?></span></li> -->
                        </ul>
                    </div>
                </div>
                <div class="portlet mt-element-ribbon light portlet-fit bordered">
                    <div class="ribbon ribbon-left ribbon-clip ribbon-shadow ribbon-border-dash-hor ribbon-color-success uppercase"><div class="ribbon-sub ribbon-clip ribbon-left"></div> <?php echo $this->translate("Thông tin nhận hàng"); ?></div>
                    <div class="portlet-title">
                        <div class="caption caption-profile">
                            <span class="caption-subject font-green bold uppercase"><?php echo $this->item['recipient_data']['fullname']; ?></span>
                        </div>
                    </div>
                    <div class="portlet-userpic">
                        <ul class="nav">
                            <?php
                                if ($this->item['recipient_data']['address'])  {
                                    echo '<li><span><i class="fa fa-home" aria-hidden="true"></i> ' . $this->item['recipient_data']['address'] . '</span></li>';
                                }
                                if ($this->item['recipient_data']['phone'])  {
                                    echo '<li><span><i class="fa fa-mobile" aria-hidden="true"></i> ' . $this->item['recipient_data']['phone'] . '</span></li>';
                                }
                            ?>
                        </ul>
                    </div>
                </div>
                <?php if ($this->discount['apply']) { ?>
                    <div class="portlet mt-element-ribbon light portlet-fit bordered">
                        <div class="ribbon ribbon-left ribbon-clip ribbon-shadow ribbon-border-dash-hor ribbon-color-success uppercase"><div class="ribbon-sub ribbon-clip ribbon-left"></div> Áp dụng mã giảm giá</div>
                        <div class="portlet-title"></div>
                        <div class="portlet-userpic">
                            <ul class="nav">
                                <li><span style="color: #f60; font-weight: 600;"><?php echo $this->discount['apply']['message']; ?></span></li>
                                <?php foreach ($this->discount['apply']['list'] as $name) {
                                    echo '<li><span><i class="fa fa-angle-right" aria-hidden="true"></i>'.$name.'</span></li>';
                                } ?>
                            </ul>
                        </div>
                    </div>
                <?php } ?>
            </div>
            <div class="col-md-8">
                <div class="profile-content">
                    <div class="portlet light ">
                        <div class="portlet-title tabbable-line">
                            <div class="caption caption-md">
                                <i class="icon-globe theme-font hide"></i>
                                <span class="caption-subject font-blue-madison bold uppercase"><?php echo $this->translate("Chi tiết đơn hàng"); ?> <span class="font-red">#<?php echo $this->item['orderCode']; ?></span></span>
                            </div>
                        </div>
                        <div class="portlet-body">
                            <table class="table table-striped table-bordered table-hover">
                                <thead>
                                    <tr>
                                        <?php
                                            foreach ($this->headers as $header) {
                                                echo '<th class="text-center" width="' . $header['width'] . '">' . $header['title'] . '</th>';
                                            }
                                        ?>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($this->list as $value) { ?>
                                        <?php
                                            $product_meta = json_decode($value['product_meta'], true);
                                            $package = $product_meta['package'] ? '<div class="option">Lựa chọn: <span>'.$product_meta['package'].'</span></div>':'';
                                        ?>
                                        <tr>
                                            <?php
                                                foreach ($this->headers as $header) {
                                                    $val = $product_meta[$header['name']];
                                                    switch ($header['name']) {
                                                        case 'thumbnail':
                                                            $thumbnail = UPLOAD_IMAGES.date('Y/m',explode('-', $val)[0]).'/autox30-'.$val;
                                                            $thumbnail = file_exists(ROOT_PUBLIC.'/'.$thumbnail) ? PUBLIC_PATH.$thumbnail : BE_TEMPLATE.'/layouts/layout/img/noimage.png';
                                                            echo '<td class="text-center"> <img src="' . $thumbnail . '"/> </td>';
                                                            break;
                                                        case 'name':
                                                            $linkProduct = $this->url('admincp',array('controller' => 'product_tb','action' => 'field','id' => $product_meta['id'],'root_id' => $product_meta['root_id']));
                                                            echo '<td><div class="name"><a href="' . $linkProduct . '" class="text-bold">' . $val . '</a></div>'.$package.'</td>';
                                                            break;
                                                        case 'quantity':
                                                            echo '<td class="text-center"> x' . $val . '</td>';
                                                            break;
                                                        case 'price':
                                                            $price = $val ? $this->formatCurrency($val).'đ' : '-';
                                                            echo '<td class="text-center">' . $price . '</td>';
                                                            break;
                                                        case 'sum':
                                                            $sum = $product_meta['price'] ? $this->formatCurrency($product_meta['price']*$value['quantity']).'đ' : '-';
                                                            echo '<td class="text-center text-bold">' . $sum . '</td>';
                                                            break;
                                                        default:
                                                            echo '<td>' . $val . '</td>';
                                                            break;
                                                    }
                                                }
                                            ?>
                                        </tr>
                                        <?php if ($product_meta['root_id'] == 16 && $product_meta['comboList']) { ?>
                                            <tr>
                                                <td colspan="7">
                                                    <table class="table table-striped table-bordered" style="margin-bottom: 0">
                                                        <?php foreach ($product_meta['comboList'] as $comboItem) { ?>
                                                            <?php
                                                                $thumbnail = UPLOAD_IMAGES.date('Y/m',explode('-',$comboItem['thumbnail'])[0]).'/autox30-'.$comboItem['thumbnail'];
                                                                $thumbnail = file_exists(ROOT_PUBLIC.'/'.$thumbnail) ? PUBLIC_PATH.$thumbnail : BE_TEMPLATE.'/layouts/layout/img/noimage.png';
                                                            ?>
                                                            <tr>
                                                                <td class="text-center" width="40" style="padding: 2px;"> <img src="<?php echo $thumbnail; ?>"/> </td>
                                                                <td>
                                                                    <div class="name"><?php echo $comboItem['parentName']; ?></div>
                                                                    <div class="option">Lựa chọn: <span><?php echo $comboItem['name']; ?></span></div>
                                                                    <div class="price">Đơn giá: <span><?php echo $this->formatCurrency($comboItem['price']); ?>đ</span></div>
                                                                </td>
                                                            </tr>
                                                        <?php } ?>
                                                    </table>
                                                </td>
                                            </tr>
                                        <?php } ?>
                                    <?php } ?>
                                    <?php if ($this->_field['total_price']) { ?>
                                        <?php $colspan = $this->_field['quantity'] ? count($this->headers) - 1 : count($this->headers) - 2; ?>
                                        <tr>
                                            <td class="text-right" colspan="<?php echo $colspan ?>"> Tạm tính </td>
                                            <td class="text-right text-bold"><?php echo $this->formatCurrency($this->item['total_sum']); ?></td>
                                        </tr>
                                        <?php if ($this->_field['shipping_fee']) { ?>
                                            <tr>
                                                <td class="text-right" colspan="<?php echo $colspan ?>"> <?php echo $this->_field['shipping_fee']; ?> </td>
                                                <td class="text-right"><?php echo $this->formatCurrency($this->item['shipping_fee']); ?></td>
                                            </tr>
                                        <?php } ?>
                                        <?php if ($this->_field['extraDiscount'] && $this->item['extraDiscount']) { ?>
                                            <tr>
                                                <td class="text-right" colspan="<?php echo $colspan; ?>"> <?php echo $this->_field['extraDiscount']; ?> </td>
                                                <td class="text-right" style="color: #f60;">- <?php echo $this->formatCurrency($this->item['extraDiscount']); ?></td>
                                            </tr>
                                        <?php } ?>
                                        <?php if ($this->discount['apply']) { ?>
                                            <tr>
                                                <td class="text-right" colspan="<?php echo $colspan; ?>"> Áp dụng mã giảm giá </td>
                                                <td class="text-right" style="color: #f60;">- <?php echo $this->formatCurrency($this->discount['apply']['reducedCash']); ?></td>
                                            </tr>
                                        <?php } ?>
                                        <tr>
                                            <td class="text-right bold" colspan="<?php echo $colspan; ?>"> <?php echo $this->translate("Tổng cộng"); ?> </td>
                                            <td class="text-right"> <strong><?php echo $this->formatCurrency($this->item['total_price']); ?></strong> </td>
                                        </tr>
                                    <?php } ?>
                                </tbody>
                            </table>
                        </div>
                        <div class="portlet-title tabbable-line orderInfo">
                            <div class="caption caption-md">
                                <i class="icon-globe theme-font hide"></i>
                                <span class="caption-subject text-bold">Phương thức thanh toán:</span>
                                <span class="caption-subject bold orange"><?php echo $this->item['paymentType']; ?></span>
                            </div>
                            <?php if($this->item['paymentStatus']) { ?>
                                <div class="caption caption-md">
                                    <i class="icon-globe theme-font hide"></i>
                                    <span class="caption-subject text-bold">Trạng thái thanh toán:</span>
                                    <span class="caption-subject bold orange"><?php echo $this->item['paymentStatus']; ?></span>
                                </div>
                            <?php } if($this->item['shippingType']) { ?>
                                <div class="caption caption-md">
                                    <i class="icon-globe theme-font hide"></i>
                                    <span class="caption-subject text-bold">Hình thức giao hàng:</span>
                                    <span class="caption-subject bold orange"><?php echo $this->item['shippingType']; ?></span>
                                </div>
                            <?php } ?>
                            <div class="caption caption-md">
                                <i class="icon-globe theme-font hide"></i>
                                <span class="caption-subject text-bold"><?php echo $this->translate("Yêu cầu của khách hàng"); ?></span>
                            </div>
                        </div>
                        <div class="portlet-body clearfix orderDesc">
                            <textarea class="form-control margin-bottom-10" rows="3" readonly><?php echo $this->item['comment']; ?></textarea>
                        </div>
                        <?php if ($this->discount['list']) { ?>
                            <div class="portlet-title tabbable-line">
                                <div class="caption caption-md">
                                    <i class="icon-globe theme-font hide"></i>
                                    <span class="caption-subject font-blue-madison bold uppercase"><?php echo $this->translate("Mã giảm giá phát sinh theo đơn hàng"); ?></span>
                                </div>
                            </div>
                            <div class="portlet-body">
                                <table class="table table-striped table-bordered table-hover">
                                    <thead>
                                        <tr>
                                            <th> <?php echo $this->discount['menu']['define']['sku'] ?> </th>
                                            <th> <?php echo $this->discount['menu']['define']['discount_value'] ?> </th>
                                            <th> <?php echo $this->discount['menu']['define']['expired_number'] ?> </th>
                                            <th> <?php echo $this->discount['menu']['define']['expired_date'] ?> </th>
                                            <th class="text-center"> Chức năng </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($this->discount['list'] as $value) { ?>
                                            <?php
                                                $linkField = $this->url('admincp',array('controller' => 'product_discount_tb','action' => 'field','id' => $value['id'],'root_id' => $this->discount['menu']['id']), array('query' => array_filter(array('order_id' => $this->_params['id']), 'strlen')));
                                                $linkSendMail = $this->url('admincp',array('controller' => 'product_discount_tb','action' => 'sendMail','id' => $value['id'],'root_id' => $this->discount['menu']['id']), array('query' => array_filter(array('order_id' => $this->_params['id']), 'strlen')));
                                                $linkDelete = $this->url('admincp',array('controller' => 'product_discount_tb','action' => 'delete','id' => $value['id'],'root_id' => $this->discount['menu']['id']));
                                            ?>
                                            <tr>
                                                <td><a href="<?php echo $linkField; ?>"><?php echo $value['sku']; ?></a></td>
                                                <td> <?php echo $this->formatCurrency($value['discount_value']).' ('.($value['discount_type'] == 1 ? '%' : '$').')'; ?> </td>
                                                <td> <?php echo $value['remain'].' / '.($value['expired_number'] > 0 ? $value['expired_number'] : '~'); ?></td>
                                                <td> <?php echo $value['expired_date'] ?? '-'; ?> </td>
                                                <td class="text-center">
                                                    <div class="btn-group btn-group-sm btn-group-solid">
                                                        <a href="<?php echo $linkField; ?>" class="btn btn-sm blue">Sửa</a>
                                                        <a href="javascript:;" onclick="_HTSend.mail('<?php echo $linkSendMail; ?>');" class="btn btn-sm green ">Gửi mail</a>
                                                        <a href="javascript:;" onclick="_HTDelete.item('<?php echo $linkDelete; ?>', true);" class="btn btn-sm red">Xóa</a>
                                                    </div>
                                                </td>
                                            </tr>
                                        <?php } ?>
                                    </tbody>
                                </table>
                            </div>
                        <?php } ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
