<div class="page-content">
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li><a href="<?php echo $this->url('admincp'); ?>"><?php echo $this->translate("Trang chủ"); ?></a><i class="fa fa-circle"></i></li>
            <li><a href="<?php echo $this->linkList; ?>"><?php echo explode('/', $this->_params['title'])[0]; ?></a><i class="fa fa-circle"></i></li>
            <li><span><?php echo explode('/', $this->_params['title'])[1]; ?></span></li>
        </ul>
    </div>
    <form id="form-add" action="" method="POST" enctype="multipart/form-data" onchange="setIsChangeValue();" onkeydown="setIsChangeValue();">
        <div class="portlet box blue margin-bottom-0">
            <div class="portlet-title">
                <div class="caption"><?php echo $this->translate("Thông tin chi tiết"); ?> </div>
                <div class="actions">
                    <button type="submit" onclick="_HTSend.form(this)" class="btn btn-sm green-jungle"><i class="fa fa-check-square-o"></i> <?php echo $this->translate("Lưu"); ?></button>
                    <a href="<?php echo $this->linkList; ?>" class="btn btn-sm red"><i class="fa fa-share"></i> <?php echo $this->translate("Thoát"); ?></a>
                </div>
            </div>
            <div class="portlet-body form form-help-freeze">
                <div class="form-body">
                    <?php if ($this->error) { ?>
                        <div class="alert alert-danger display-block">
                            <button class="close" data-close="alert"></button>
                            <?php foreach ($this->error as $error) { echo '<p>'.$error.'</p>'; } ?>
                        </div>
                    <?php } ?>
                    <div class="row">
                        <?php echo $this->partialLoop('partials/form-addedit.phtml', array(array('default' => $this->elements))); ?>
                    </div>
                    <div class="row margin-top-10">
                        <div class="col-md-12">
                            <div class="portlet light bordered">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <i class="icon-settings font-blue-sharp"></i>
                                        <span class="caption-subject font-blue-sharp bold uppercase">Quyền truy cập</span>
                                    </div>
                                </div>
                                <div class="portlet-body">
                                    <div id="tree_permission" class="tree-demo"></div>
                                    <input id="input_permission" type="hidden" name="permission" value="" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-actions right">
                    <button type="submit" onclick="_HTSend.form(this)" class="btn btn-sm green-jungle"><i class="fa fa-check-square-o"></i> <?php echo $this->translate("Lưu"); ?></button>
                    <a href="<?php echo $this->linkList; ?>" class="btn btn-sm red"><i class="fa fa-share"></i> <?php echo $this->translate("Thoát"); ?></a>
                </div>
            </div>
        </div>
    </form>
</div>
<script>
    $(document).ready(function() {
        FormValidation.submit('#form-add', { rules:{ name:{ required: true }}});
        UITree.init(Object.values($.parseJSON('<?php echo json_encode($this->menu); ?>')));
    });
</script>