<div class="page-content">
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li><a href="<?php echo $this->url('admincp'); ?>"><?php echo $this->translate("Trang chủ"); ?></a><i class="fa fa-circle"></i></li>
            <li><span><?php echo $this->_params['title']; ?></span></li>
        </ul>
    </div>
    <div class="portlet box blue margin-bottom-0">
        <div class="portlet-title">
            <div class="caption"><?php echo $this->translate("Danh sách"); ?> </div>
            <div class="actions">
                <a href="<?php echo $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'field','root_id' => $this->_params['root_id'])); ?>" class="btn yellow"><i class="fa fa-plus-square-o"></i> <?php echo $this->translate("Thêm mới"); ?></a>
            </div>
        </div>
        <div class="portlet-body">
            <table id="datatable-default" class="table table-striped table-bordered table-hover table-checkable">
                <thead>
                    <tr>
                        <th class="table-sort"> ID </th>
                        <th> <?php echo $this->translate("Nhóm quyền"); ?> </th>
                        <th class="nosort nosearch table-func"> <?php echo $this->translate("Chức năng"); ?> </th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->list as $value) { ?>
                        <tr class="odd gradeX">
                            <td><?php echo $value['id']; ?></td>
                            <td><a href="<?php echo $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'field','id' => $value['id'],'root_id' => $this->_params['root_id'])); ?>"><?php echo $value['name']; ?></a></td>
                            <td>
                                <div class="text-center">
                                    <div class="btn-group btn-group-sm btn-group-solid">
                                        <a href="<?php echo $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'field','id' => $value['id'],'root_id' => $this->_params['root_id'])); ?>" class="btn blue"><?php echo $this->translate("Sửa"); ?></a>
                                        <?php if ($value['id'] != 1) { ?>
                                        <a href="javascript:;" class="btn red" onclick="_HTDelete.item('<?php echo $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'delete','id' => $value['id'])); ?>');"><?php echo $this->translate("Xóa"); ?></a>
                                        <?php } ?>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        TableDatatables.init({
            destroy: true,
            ordering: false,
            pageLength: -1,
        });
    });
</script>