<?php
    $action = ($this->head[$this->data['position']][$this->data['action']]) ? $this->head[$this->data['position']][$this->data['action']] : array();
    $global = ($this->head[$this->data['position']]['global']) ? $this->head[$this->data['position']]['global'] : array();
    $styles = array_merge_recursive($global, $action);

    foreach ($styles as $type => $files) {
        $i = 0;
        foreach ($files as $key => $file) {
            $filename = is_string($key) ? $key : $file;
            $path = 'template/frontend/dist/'.$type.'/'.$filename;
            if ($type == 'css') {
                if ($file == 'global.css') {
                    echo "<link type=\"text/css\" rel=\"stylesheet\" href=\"".PUBLIC_PATH.$path."\">\n";
                } else {
                    echo '<style type="text/css" media="screen">'.file(ROOT_PUBLIC.'/'.$path)[0].'</style>'."\n";
                }
            }
            if ($type == 'js') {
                $i++;
                $attrs = is_string($key) ? array($file => $file) : '';
                if ($file == 'global.js') {
                    $this->headScript()->offsetSetFile(($i-20), PUBLIC_PATH.$path, 'text/javascript', $attrs);
                } else {
                    $this->headScript()->offsetSetScript(($i-20), file(ROOT_PUBLIC.'/'.$path)[0], 'text/javascript', $attrs);
                }
            }
        }
    }
?>