<div class="page-content">
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li><a href="<?php echo $this->url('admincp'); ?>"><?php echo $this->translate("Trang chủ"); ?></a><i class="fa fa-circle"></i></li>
            <li><span><?php echo $this->_params['title']; ?></span></li>
        </ul>
        <?php if ($this->identity()->supper) { ?>
            <a href="<?php echo $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'codefield','root_id' => $this->_params['root_id'])); ?>" class="btn green pull-right"><i class="fa fa-cogs"></i> Cấu hình dữ liệu</a>
        <?php } ?>
    </div>
    <div class="portlet box blue margin-bottom-0">
        <div class="portlet-title">
            <div class="caption"><?php echo $this->translate("Danh sách"); ?> </div>
            <?php if ($this->identity()->supper) { ?>
            <div class="actions">
                <a href="<?php echo $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'field','root_id' => $this->_params['root_id'])); ?>" class="btn yellow"><i class="fa fa-plus-square-o"></i> <?php echo $this->translate("Thêm"); ?></a>
            </div>
            <?php } ?>
        </div>
        <div class="portlet-body">
            <table id="datatable-default" class="table table-striped table-bordered table-hover table-checkable">
                <thead>
                    <tr>
                    <?php
                        echo '<th class="table-checkall"> ID </th>';
                        echo '<th> Menu </th>';
                        if ($this->identity()->supper) {
                            echo '<th> Active </th>';
                            echo '<th> Link </th>';
                            echo '<th class="table-sort">'.$this->translate("Sắp xếp").'</th>';
                            if ($this->identity()->lang && count($this->identity()->langlist) > 1) {
                                echo '<th class="nosearch table-lang"><span>'.$this->translate("Hiển thị").'</span><span>';
                                foreach ($this->identity()->langlist as $item) { echo '<span>'.$item[0].'</span>'; }
                                echo '</span></th>';
                            }
                            echo '<th class="nosearch table-show">'.$this->translate("Hiển thị").'</th>';
                        }
                        foreach ($this->_field['special'] as $item) {
                            echo '<th class="nosearch table-show"><span class="d-flex justify-content--center"><span class="flex-none">' . $this->translate($item['label']).'</span>&nbsp;<a href="javascript:;" class="tooltips '.($item['note'] ? '' : 'hidden').'" data-container="body" title="'.$item['note'].'"><i class="fa fa-question-circle" aria-hidden="true"></i></a></span></th>';
                        }
                        echo '<th class="nosort nosearch table-func">'.$this->translate("Chức năng").'</th>';
                    ?>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->list as $value) { ?>
                        <?php
                            $linkField = $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'field','id' => $value['id'],'root_id' => $this->_params['root_id']));
                            $linkChange = $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'change','id' => $value['id']));
                            $linkDelete = $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'delete','id' => $value['id'],'root_id' => $this->_params['root_id']));
                            $value['define'] = $value['define'] ? json_decode($value['define'], true) : array();
                            $langDislay = array();
                            if ($value['l.id']) {
                                // 0: id, 1: display, 2: name
                                $langDislay = array_merge_recursive(
                                    array_combine(explode('#@#',$value['l.language']), explode('#@#',$value['l.id'])),
                                    array_combine(explode('#@#',$value['l.language']), explode('#@#',$value['l.display'])),
                                    array_combine(explode('#@#',$value['l.language']), explode('#@#',$value['l.name']))
                                );
                                $value['name'] = ($langDislay[$this->identity()->lang][2]) ? $langDislay[$this->identity()->lang][2] : $value['name'];
                            }
                        ?>
                        <tr class="odd gradeX">
                        <?php
                            echo '<td>'.$value['id'].'</td>';
                            echo '<td><a href="'.$linkField.'" class="level'.(($value['parent'] > 0 ? $value['level'] : 0) + 1).'">'.$value['name'].'</a></td>';
                            if ($this->identity()->supper) {
                                echo '<td>'.$value['active'].'</td>';
                                echo '<td>'.$value['link'].'</td>';
                                echo '<td><input type="text" name="sort" class="form-control text-center input-sm" onkeydown="_HTChange.sort(this, \''.$linkChange.'\');" value="'.$value['sort'].'" /></td>';
                                if ($this->identity()->lang && count($this->identity()->langlist) > 1) {
                                    echo '<td class="text-center table-lang">';
                                        foreach ($this->identity()->langlist as $item) {
                                            if ($langDislay[$item[0]]) {
                                                echo '<label class="mt-checkbox mt-checkbox-outline"><input type="checkbox" name="display" value="'.$langDislay[$item[0]][1].'" onclick="_HTChange.status(this, \'switch\', '.htmlspecialchars(json_encode(array('url' => $this->url('admincp',array('controller' => 'lang_multi_tb','action' => 'change','id' => $langDislay[$item[0]][0]))), JSON_UNESCAPED_SLASHES)).');" '.($langDislay[$item[0]][1] ? 'checked' : '').' /><span class="text-hide">'.$langDislay[$item[0]][1].'</span></label>';
                                            }
                                        }
                                    echo '</td>';
                                }
                                echo '<td class="text-center"><label class="mt-checkbox mt-checkbox-outline"><input type="checkbox" name="display" value="'.$value['display'].'" onclick="_HTChange.status(this, \'switch\', '.htmlspecialchars(json_encode(array('url' => $linkChange), JSON_UNESCAPED_SLASHES)).');" '.($value['display'] ? 'checked' : '').' /><span class="text-hide">'.$value['display'].'</span></label></td>';
                            }
                            if ($this->_field['special']) {
                                $special = ($value['special']) ? json_decode($value['special'], true) : array();
                                foreach ($this->_field['special'] as $item) {
                                    $vl_special = ($special[$item['name']]) ? 1 : 0;
                                    echo '<td class="text-center"><label class="mt-checkbox mt-checkbox-outline"><input type="checkbox" data-special name="'.$item['name'].'" value="'.$vl_special.'" onclick="_HTChange.special(this, \''.$linkChange.'\');" '.(($vl_special) ? 'checked' : '').' /><span class="text-hide">'.$vl_special.'</span></label></td>';
                                }
                            }
                            echo '<td><div class="text-center"><div class="btn-group btn-group-sm btn-group-solid"><a href="'.$linkField.'" class="btn blue">'.$this->translate("Sửa").'</a>'.($this->identity()->supper ? '<a href="javascript:;" class="btn red" onclick="_HTDelete.item(\''.$linkDelete.'\', true);">'.$this->translate("Xóa").'</a>' : '').'</div></div></td>';
                        ?>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        TableDatatables.init({
            destroy: true,
            ordering: false,
            pageLength: -1,
        });
    });
</script>