<?php
    $title = explode('/', $this->_params['title']);
    $title[0] = $this->linkList ? '<a href="' . $this->linkList . '">' . $title[0] . '</a>' : '<span>' . $title[0] . '</span>';
    $save = !$this->identity()->supper ? 'onclick="_HTSend.form(this)"':'';
?>
<div class="page-content">
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li><a href="<?php echo $this->url('admincp'); ?>"><?php echo $this->translate("Trang chủ"); ?></a><i class="fa fa-circle"></i></li>
            <li><?php echo $title[0]; ?><i class="fa fa-circle"></i></li>
            <li><span><?php echo $title[1]; ?></span></li>
        </ul>
        <?php if ($this->_field['codefield'] || $this->_field['codevalidate']) { ?>
            <div class="pull-right">
                <?php if ($this->_field['codevalidate']) { ?>
                    <a href="<?php echo $this->url('admincp', array('controller' => $this->_params['__CONTROLLER__'],'action' => 'codevalidate','id' => $this->_params['id'],'root_id' => $this->_params['root_id'])); ?>" class="btn green"><i class="fa fa-cogs"></i> Định nghĩa dữ liệu</a>
                <?php } ?>
                <?php if ($this->_field['codefield']) { ?>
                <a href="<?php echo $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'codefield','id' => $this->_params['id'],'root_id' => $this->_params['root_id'])); ?>" class="btn green pull-right"><i class="fa fa-cogs"></i> Cấu hình dữ liệu</a>
                <?php } ?>
            </div>
        <?php } ?>
    </div>
    <form id="form-add" action="" method="POST" enctype="multipart/form-data" onchange="setIsChangeValue();" onkeydown="setIsChangeValue();">
        <div class="portlet box blue margin-bottom-0">
            <div class="portlet-title">
                <div class="caption"><?php echo $this->translate("Thông tin chi tiết"); ?> </div>
                <div class="actions">
                    <?php if (!$this->_params['id']) { ?>
                        <label class="mt-checkbox mt-checkbox-right">
                            <input type="checkbox" value="checked" name="continue" ht-trigger="add-continue" <?php echo $this->continue; ?>/>
                            <span></span><?php echo $this->translate("Thêm mới khác"); ?>
                        </label>
                    <?php } ?>
                    <button type="submit" <?php echo $save; ?> class="btn btn-sm green-jungle"><i class="fa fa-check-square-o"></i> <?php echo $this->translate("Lưu"); ?></button>
                    <a href="<?php echo $this->linkList; ?>" class="btn btn-sm red <?php echo $this->_field['disableBtnCancel'] ? 'hide' : ''; ?>"><i class="fa fa-share"></i> <?php echo $this->translate("Thoát"); ?></a>
                </div>
            </div>
            <div class="portlet-body form form-help-freeze">
                <div class="form-body">
                    <?php if ($this->error) { ?>
                        <div class="alert alert-danger display-block">
                            <button class="close" data-close="alert"></button>
                            <?php foreach ($this->error as $error) { echo '<p>'.$error.'</p>'; } ?>
                        </div>
                    <?php } ?>
                    <?php if ($this->alertSuccess) { ?>
                        <div class="alert bg-green-jungle display-block">
                            <button class="close" data-close="alert"></button>
                            <p> <?php echo $this->alertSuccess; ?> </p>
                        </div>
                    <?php } ?>
                    <div class="tabbable-custom ">
                        <?php if (count($this->identity()->langlist) > 1) { ?>
                            <ul class="nav nav-tabs ">
                                <?php foreach ($this->identity()->langlist as $i => $lang) { ?>
                                    <li <?php echo ($i == 0) ? 'class="active"' : ''; ?>>
                                        <a href="#tab_<?php echo $lang[0]; ?>" data-toggle="tab"> <?php echo $lang[0].' - '.$this->translate($lang[1]); ?> </a>
                                    </li>
                                <?php } ?>
                            </ul>
                        <?php } ?>
                        <div <?php echo (count($this->identity()->langlist) > 1) ? 'class="tab-content"' : ''; ?>>
                            <?php foreach ($this->identity()->langlist as $i => $lang) { ?>
                                <?php if ($this->identity()->lang) {
                                    $arrsLang = array('tab' => $lang[0], 'data' => $this->item['translate'][$lang[0]], 'field' => $this->_field['validate']['translate']);
                                } ?>
                                <div class="tab-pane <?php echo ($i == 0) ? 'active' : ''; ?>" id="tab_<?php echo $lang[0]; ?>">
                                    <div class="row">
                                        <?php echo $this->partialLoop('partials/form-addedit.phtml', array(array('default' => $this->elements, 'lang' => $arrsLang))); ?>
                                    </div>
                                </div>
                            <?php } ?>
                        </div>
                    </div>
                </div>
                <div class="form-actions right">
                    <?php if (!$this->_params['id']) { ?>
                        <label class="mt-checkbox mt-checkbox-outline mt-checkbox-right">
                            <input type="checkbox" value="checked" name="continue" ht-trigger="add-continue" <?php echo $this->continue; ?>/>
                            <span></span><?php echo $this->translate("Thêm mới khác"); ?>
                        </label>
                    <?php } ?>
                    <button type="submit" <?php echo $save; ?> class="btn btn-sm green-jungle"><i class="fa fa-check-square-o"></i> <?php echo $this->translate("Lưu"); ?></button>
                    <a href="<?php echo $this->linkList; ?>" class="btn btn-sm red <?php echo $this->_field['disableBtnCancel'] ? 'hide' : ''; ?>"><i class="fa fa-share"></i> <?php echo $this->translate("Thoát"); ?></a>
                </div>
            </div>
        </div>
    </form>
</div>
<script>
    $(document).ready(function() {
        var rules = {}, checkForm = $.parseJSON('<?php echo json_encode($this->_params["checkForm"]); ?>');

        if (checkForm.required) {
            var field_required = Object.keys(checkForm.required);
            for (var i = 0; i < field_required.length; i++) {
                if (field_required[i].indexOf("thumbnail") > -1) continue;

                field_required[i] = (field_required[i] == 'cat_id' && '<?php echo $this->_field["cat_id"]; ?>' == 'checkbox') ? field_required[i]+'[]' : field_required[i];
                rules[field_required[i].replace(/\{(.*?)\}/g, "[$1]")] = {required: true};
            }
        }

        if (checkForm.exists) {
            var field_exists = Object.keys(checkForm.exists);
            for (var j = 0; j < field_exists.length; j++) {
                rules[field_exists[j]] = rules[field_exists[j]] ? Object.assign(rules[field_exists[j]], {exists: checkForm.exists[field_exists[j]]}) : {exists: checkForm.exists[field_exists[j]]};
            }
        }

        if (checkForm.url) {
            var field_url = Object.keys(checkForm.url);
            for (var k = 0; k < field_url.length; k++) {
                rules[field_url[k]] = rules[field_url[k]] ? Object.assign(rules[field_url[k]], {url: true}) : {url: true};
            }
        }

        FormValidation.submit('#form-add', {rules: rules});
    });
</script>

<?php if ($this->success) { ?>
    <script> window.location.href = '<?php echo $this->linkList; ?>'; </script>
<?php } ?>
<?php if ($this->error_code_field) { ?>
    <script> _HTTemplate.reload('<?php echo $this->error_code_field; ?>', '<?php echo $this->linkList; ?>');  </script>
<?php } ?>