<div class="container ht-mrt30">
    <div class="row">
        <div class="col-md-9 center-block">
            <div class="s-cart-1">
                <div class="c-headline-2 h1"><h1 class="c_divider">Danh sách đơn hàng của bạn</h1></div>
                <table class="s_table">
                    <tbody>
                        <tr>
                            <td><b>Mã đơn hàng</b></td>
                            <td><b>Ngày đặt hàng</b></td>
                            <td><b>Trạng thái</b></td>
                            <td><b>Tổng tiền</b></td>
                        </tr>
                        <?php if ($this->list) { ?>
                            <?php foreach ($this->list as $value) { ?>
                                <tr>
                                    <td class="ht-hover text-bold"><a href="<?php echo $value['id']; ?>-64.html" class="text--hypertext">#<?php echo $value['orderCode']; ?></a></td>
                                    <td><?php echo date('d/m/Y H:i', strtotime($value['date_created'])); ?></td>
                                    <td><?php echo $this->status[$value['status']]; ?></td>
                                    <td class="text-bold"><?php echo number_format($value['total_price'], 0,'.','.'); ?>đ</td>
                                </tr>
                            <?php } ?>
                        <?php } else { ?>
                            <tr>
                                <td class="text-center" colspan="4"><?php echo $this->translate("Bạn chưa có đơn hàng!"); ?></td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<style>
    /* Style chung S-CART */
    [class*="s-cart-"] .s_table {
        font-size: 14px;
        width: 100%;
        border-spacing: 0;
        border-collapse: collapse;
        margin-bottom: 20px;
    }
    [class*="s-cart-"] .s_table tr td {
        border-bottom: 1px solid #ccc;
        padding: 0.5em 0.22em 0.5em 0.22em;
    }
    [class*="s-cart-"] .s_table tr td:first-child {
        padding-left: 0;
    }
    [class*="s-cart-"] .s_table tr td:last-child {
        padding-right: 0;
    }
    [class*="s-cart-"] .s_table tr:last-child td {
        border: none;
    }

    /* BEGIN s-cart-1 */
    .s-cart-1 table {
      text-align: center;
    }
    @media (max-width: 575px) {
        .s-cart-1 {
            font-size: 90%;
        }
    }
    /* END s-cart-1 */
</style>