<?php echo ($this->params['keysearch'] ? '<div class="ht-mrb15">Từ khóa cần tìm: '.$this->params['keysearch'].'</div>': ''); ?>
<?php if($this->paginator->getTotalItemCount() > 0) { ?>
    <div class="row row-flex" data-items="<?php echo $this->paginator->getTotalItemCount(); ?>">
        <?php echo $this->block3(array('list' => $this->list, 'col' => 'col-6 col-md-4')); ?>
    </div>
    <?php if ($this->paginator->getTotalItemCount() > $this->paginator->getItemCountPerPage()) { ?>
    	<div class="p_more text-center ht-mrb30" style="margin-top: 0;">
            <a href="javascript:;" id="news21Y" class="c-button-4" onclick="showMore('<?php echo PUBLIC_PATH."pagination-81.html"; ?>','<?php echo htmlspecialchars(json_encode(array('page' => 2, 'limit' => $this->paginator->getItemCountPerPage(), 'id' => $this->params['id'], 'type' => 'news21Y', 'list_select_id' => $this->params['list_select_id'], 'list_label_id' => $this->params['list_label_id'], 'keysearch' => $this->params['keysearch']), JSON_UNESCAPED_UNICODE)); ?>', '.b-card-53.block-news', '#news21Y');"><span class="fa fa-angle-down"> Xem thêm</span></a>
        </div>
    <?php } ?>
<?php } else { echo '<div class="h3" style="text-transform: uppercase;margin: 5px 0;color: #03707d;">Không tìm thấy bài viết</div>'; } ?>