<div class="page-content">
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li><a href="<?php echo $this->url('admincp'); ?>"><?php echo $this->translate("Trang chủ"); ?></a><i class="fa fa-circle"></i></li>
            <li><span><?php echo $this->_params['title']; ?></span></li>
        </ul>
        <?php if ($this->identity()->supper) { ?>
            <a href="<?php echo $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'codefield','root_id' => $this->_params['root_id'])); ?>" class="btn green pull-right"><i class="fa fa-cogs"></i> Cấu hình dữ liệu</a>
        <?php } ?>
    </div>
    <div class="portlet box blue margin-bottom-0">
        <div class="portlet-title">
            <div class="caption"><?php echo $this->translate("Danh sách"); ?> </div>
            <div class="actions">
                <?php if ($this->_field['add']) { ?>
                    <a href="<?php echo $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'field','root_id' => $this->_params['root_id'])); ?>" class="btn yellow"><i class="fa fa-plus-square-o"></i> <?php echo $this->translate("Thêm"); ?></a>
                <?php } if ($this->_field['delete']) { ?>
                    <a href="javascript:;" class="btn red" onclick="_HTDelete.rows('<?php echo $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'delete')); ?>','/root_id=<?php echo $this->_params['root_id']; ?>');"><i class="fa fa-trash-o"></i> <?php echo $this->translate("Xóa nhiều"); ?></a>
                <?php } ?>
            </div>
        </div>
        <div class="portlet-body">
            <table id="datatable-default" class="table table-striped table-bordered table-hover table-checkable">
                <thead>
                    <tr>
                        <th class="nosort nosearch table-checkall">
                            <label class="mt-checkbox mt-checkbox-outline">
                                <input type="checkbox" class="group-checkable" data-set=".ht-checkall-rows" />
                                <span></span>
                            </label>
                        </th>
                        <th class="table-checkall"> ID </th>
                        <th> <?php echo $this->translate($this->_field['name']); ?> </th>
                        <th> News ID </th>
                        <?php if ($this->_field['sort']) { ?>
                            <th class="table-sort"><div class="d-flex justify-content--center"><span class="flex-none"><?php echo $this->translate("Sắp xếp"); ?></span>&nbsp;<a href="javascript:;" class="tooltips" data-container="body" title="Đánh số để sắp xếp thứ tự hiển thị theo ý muốn. Nguyên tắc số nhỏ hơn sẽ nằm phía trên."><i class="fa fa-question-circle" aria-hidden="true"></i></a></div></th>
                        <?php } ?>
                        <?php if ($this->identity()->lang && count($this->identity()->langlist) > 1) { ?>
                            <th class="nosearch table-lang">
                                <span class="d-flex justify-content--center"><span class="flex-none"><?php echo $this->translate("Hiển thị"); ?></span><a href="javascript:;" class="tooltips" data-container="body" title="Tick chọn để hiển thị trên website, bỏ tick để ẩn đi"><i class="fa fa-question-circle" aria-hidden="true"></i></a></span>
                                <span><span><?php echo implode('</span><span>', array_column($this->identity()->langlist, 0)); ?></span></span>
                            </th>
                        <?php } ?>
                        <?php if ($this->_field['display']) { ?>
                            <th class="nosearch table-show"><div class="d-flex justify-content--center"><span class="flex-none"><?php echo $this->translate("Hiển thị"); ?></span>&nbsp;<a href="javascript:;" class="tooltips" data-container="body" title="Tick chọn để hiển thị trên website, bỏ tick để ẩn đi"><i class="fa fa-question-circle" aria-hidden="true"></i></a></div></th>
                        <?php } ?>
                        <?php if ($this->_field['add'] || $this->_field['delete']) { ?>
                            <th class="nosort nosearch table-func <?php echo ($this->_field['copy']) ? 'copy' : ''; ?>"> <?php echo $this->translate("Chức năng"); ?> </th>
                        <?php } ?>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->list as $value) { ?>
                        <?php
                            $linkField = $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'field','id' => $value['id'],'root_id' => $this->_params['root_id']));
                            $linkChange = $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'change','id' => $value['id']));
                            $linkDelete = $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'delete','id' => $value['id'],'root_id' => $this->_params['root_id']));
                            $langDislay = array();
                            if ($value['l.id']) {
                                // 0: id, 1: display, 2: name
                                $langDislay = array_merge_recursive(
                                    array_combine(explode('#@#',$value['l.language']), explode('#@#',$value['l.id'])),
                                    array_combine(explode('#@#',$value['l.language']), explode('#@#',$value['l.display'])),
                                    array_combine(explode('#@#',$value['l.language']), explode('#@#',$value['l.name']))
                                );
                                $value['name'] = ($langDislay[$this->identity()->lang][2]) ? $langDislay[$this->identity()->lang][2] : $value['name'];
                            }
                        ?>
                        <tr class="odd gradeX">
                            <td>
                                <label class="mt-checkbox mt-checkbox-outline">
                                    <input type="checkbox" class="ht-checkall-rows" value="<?php echo $value['id']; ?>" />
                                    <span></span>
                                </label>
                            </td>
                            <td> <?php echo $value['id']; ?> </td>
                            <td>
                                <a href="<?php echo $linkField; ?>"><?php echo $value['name'].'<span class="font-red"> ('.($value['list_news_id'] ? count(explode(',', $value['list_news_id'])) : 0).')</span>'; ?></a>
                                <?php
                                    if ($this->_field['icon-link-web'] != 'none') {
                                        $routerParams = array_merge(array('%slug%' => $value['slug'], '%tag_id%' => $value['id']), $this->router['params']);
                                        $linkTag = PUBLIC_PATH.str_replace(array_keys($routerParams), array_values($routerParams), $this->router['spec']);
                                        echo '<a href="'.$linkTag.'" target="_blank" class="pull-right"><i class="fa fa-external-link" aria-hidden="true"></i></a>';
                                    }
                                ?>
                            </td>
                            <td> <?php echo $value['list_news_id'] ? str_replace(':',' ',$value['list_news_id']) : '-'; ?> </td>
                            <?php if ($this->_field['sort']) { ?>
                                <td>
                                    <input type="text" name="sort" class="form-control text-center input-sm" onkeydown="_HTChange.sort(this, '<?php echo $linkChange; ?>');" value="<?php echo $value['sort']; ?>" /><span class="text-hide"><?php echo $value['sort']; ?></span>
                                </td>
                            <?php } ?>
                            <?php if ($this->identity()->lang && count($this->identity()->langlist) > 1) { ?>
                                <td class="text-center table-lang">
                                    <?php foreach ($this->identity()->langlist as $item) { ?>
                                        <?php if ($langDislay[$item[0]]) { ?>
                                            <label class="mt-checkbox mt-checkbox-outline">
                                                <input type="checkbox" name="display" value="<?php echo $langDislay[$item[0]][1]; ?>" onclick="_HTChange.status(this, 'switch', <?php echo htmlspecialchars(json_encode(array('url' => $this->url('admincp',array('controller' => 'lang_multi_tb','action' => 'change','id' => $langDislay[$item[0]][0]))), JSON_UNESCAPED_SLASHES)); ?>);" <?php echo ($langDislay[$item[0]][1]) ? 'checked' : ''; ?> />
                                                <span class="text-hide"><?php echo $langDislay[$item[0]][1]; ?></span>
                                            </label>
                                        <?php } ?>
                                    <?php } ?>
                                </td>
                            <?php } ?>
                            <?php if ($this->_field['display']) { ?>
                                <td class="text-center">
                                    <label class="mt-checkbox mt-checkbox-outline">
                                        <input type="checkbox" name="display" value="<?php echo $value['display']; ?>" onclick="_HTChange.status(this, 'switch', <?php echo htmlspecialchars(json_encode(array('url' => $linkChange), JSON_UNESCAPED_SLASHES)); ?>);" <?php echo ($value['display']) ? 'checked' : ''; ?> />
                                        <span class="text-hide"><?php echo $value['display']; ?></span>
                                    </label>
                                </td>
                            <?php } ?>
                            <?php if ($this->_field['add'] || $this->_field['delete'] || $this->_field['copy']) { ?>
                                <td>
                                    <div class="text-center">
                                        <div class="btn-group btn-group-sm btn-group-solid">
                                            <?php if ($this->_field['copy']) { ?>
                                                <a href="<?php echo $linkField.'?action=copy'; ?>" class="btn yellow">Copy</a>
                                            <?php } if ($this->_field['add']) { ?>
                                                <a href="<?php echo $linkField; ?>" class="btn blue"><?php echo $this->translate("Sửa"); ?></a>
                                            <?php } if ($this->_field['delete']) { ?>
                                                <a href="javascript:;" class="btn red" onclick="_HTDelete.item('<?php echo $linkDelete; ?>');"><?php echo $this->translate("Xóa"); ?></a>
                                            <?php } ?>
                                        </div>
                                    </div>
                                </td>
                            <?php } ?>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>