<div class="page-content">
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li><a href="<?php echo $this->url('admincp'); ?>"><?php echo $this->translate("Trang chủ"); ?></a><i class="fa fa-circle"></i></li>
            <li><a href="<?php echo $this->linkList; ?>"><?php echo explode('/', $this->_params['title'])[0]; ?></a><i class="fa fa-circle"></i></li>
            <li><span><?php echo explode('/', $this->_params['title'])[1]; ?></span></li>
        </ul>
    </div>
    <form id="form-add" action="" method="POST" enctype="multipart/form-data" onchange="setIsChangeValue();" onkeydown="setIsChangeValue();">
        <div class="portlet box blue margin-bottom-0">
            <div class="portlet-title">
                <div class="caption"><?php echo $this->translate("Thông tin chi tiết"); ?> </div>
                <div class="actions">
                    <?php
                        $buttons = '';
                        $appendValueStatusPublish = htmlspecialchars(json_encode(array('status' => 1), JSON_UNESCAPED_SLASHES));
                        $appendValueStatusBrowse = htmlspecialchars(json_encode(array('status' => 0), JSON_UNESCAPED_SLASHES));
                        $appendValueStatusNotBrowse = htmlspecialchars(json_encode(array('status' => -1), JSON_UNESCAPED_SLASHES));
                        $appendValueStatusDraf = htmlspecialchars(json_encode(array('status' => -2), JSON_UNESCAPED_SLASHES));
                        $appendValueStatusItSelf = htmlspecialchars(json_encode(array('status' => $this->item['status']), JSON_UNESCAPED_SLASHES));

                        $publish = !$this->identity()->supper ? 'onclick="_HTSend.form(this, '.$appendValueStatusPublish.')"':'';
                        $browser = !$this->identity()->supper ? 'onclick="_HTSend.form(this, '.$appendValueStatusBrowse.')"':'';
                        $draf = !$this->identity()->supper ? 'onclick="_HTSend.form(this, '.$appendValueStatusDraf.')"':'';
                        $save = !$this->identity()->supper ? 'onclick="_HTSend.form(this)"':'';
                        $saveSelf = !$this->identity()->supper ? 'onclick="_HTSend.form(this, '.$appendValueStatusItSelf.')"':'';
                        $notBrowse = !$this->identity()->supper ? 'onclick="_HTSend.form(this, '.$appendValueStatusNotBrowse.')"':'';

                        if (!$this->_params['id']) {
                            $buttons .= '<label class="mt-checkbox mt-checkbox-right"><input type="checkbox" value="checked" name="continue" ht-trigger="add-continue" '.$this->continue.'/><span></span>'.$this->translate("Thêm mới khác").'</label>';
                            if ($this->_field['status'] && !$this->_params['permission']['status']) {
                                $buttons .= '<div class="btn-group btn-status">
                                    <button type="submit" '.$browser.' class="btn btn-sm green-jungle"><i class="fa fa-newspaper-o"></i> Gửi duyệt</button>
                                    <button type="submit" '.$draf.' class="btn btn-sm yellow"><i class="fa fa-pencil"></i> Lưu nháp</button>
                                </div>';
                            } elseif ($this->_params['permission']['add']) {
                                if ($this->_field['draft'] || ($this->_params['permission']['status'] && $this->_field['status'])) {
                                    $buttons .= '<div class="btn-group btn-status">
                                        <button type="submit" '.$publish.' class="btn btn-sm green-jungle"><i class="fa fa-newspaper-o"></i> Xuất bản</button>
                                        <button type="submit" '.$draf.' class="btn btn-sm yellow"><i class="fa fa-pencil"></i> Lưu nháp</button>
                                    </div>';
                                } else {
                                    $buttons .= '<button type="submit" '.$save.' class="btn btn-sm green-jungle"><i class="fa fa-check-square-o"></i> '.$this->translate("Lưu").'</button>';
                                }
                            }
                        } elseif ($this->_field['status'] && in_array($this->item['status'], array(-2,-1,0)) && $this->_params['permission']['edit']) {
                            if ($this->item['status'] == -2 && $this->_params['permission']['status']) {
                                $buttons .= '<div class="btn-group btn-status">
                                    <button type="submit" '.$publish.' class="btn btn-sm green-jungle"><i class="fa fa-newspaper-o"></i> Xuất bản</button>
                                    <button type="submit" '.$draft.' class="btn btn-sm yellow"><i class="fa fa-pencil"></i> Lưu nháp</button>
                                </div>';
                            } else {
                                $buttons .= '<div class="btn-group btn-status">';
                                    if (in_array($this->item['status'], array(-2, -1)) && !$this->_params['permission']['status']) {
                                        $buttons .= '<button type="submit" '.$browser.' class="btn btn-sm green-jungle"><i class="fa fa-newspaper-o"></i> Gửi duyệt</button>';
                                    } else if ($this->_params['permission']['status']) {
                                        $buttons .= '<button type="submit" '.$publish.' class="btn btn-sm green-jungle"><i class="fa fa-newspaper-o"></i> Xuất bản</button>';
                                    }
                                    if ($this->item['status'] == 0 && $this->_params['permission']['status']) {
                                        $buttons .= '<button type="submit" '.$notBrowse.' class="btn btn-sm grey-salsa"><i class="fa fa-ban"></i> Không duyệt</button>';
                                    }
                                    $buttons .= '<button type="submit" '.$saveSelf.' class="btn btn-sm yellow"><i class="fa fa-pencil"></i> Lưu</button>';
                                $buttons .= '</div>';
                            }
                        } elseif (($this->_params['permission']['edit'] && $this->_params['permission']['status']) || $this->_params['permission']['d-status']) {
                            if ($this->_field['draft'] && $this->item['status'] == -2) {
                                $buttons .= '<div class="btn-group btn-status">
                                    <button type="submit" '.$publish.' class="btn btn-sm green-jungle"><i class="fa fa-newspaper-o"></i> Xuất bản</button>
                                    <button type="submit" '.$draft.' class="btn btn-sm yellow"><i class="fa fa-pencil"></i> Lưu nháp</button>
                                </div>';
                            } else {
                                $buttons .= '<button type="submit" '.$save.' class="btn btn-sm green-jungle"><i class="fa fa-check-square-o"></i> '.$this->translate("Lưu").'</button>';
                            }
                        }
                        $buttons .= ' <a href="'. $this->linkList. '" class="btn btn-sm red"><i class="fa fa-share"></i> Thoát</a>';

                        echo $buttons;
                    ?>
                </div>
            </div>
            <div class="portlet-body form form-help-freeze">
                <div class="form-body">
                    <?php if($this->_params['id']) { ?>
                        <span style="margin-bottom: 15px;display: block; font-style: italic;">Ngày đăng bài: <?php echo date('d-m-Y H:i', strtotime($this->item['date_published'])); ?></span>
                    <?php } ?>
                    <?php if ($this->error) { ?>
                        <div class="alert alert-danger display-block">
                            <button class="close" data-close="alert"></button>
                            <?php foreach ($this->error as $error) { echo '<p>'.$error.'</p>'; } ?>
                        </div>
                    <?php } ?>
                    <div class="tabbable-custom">
                        <?php if (count($this->identity()->langlist) > 1) { ?>
                            <ul class="nav nav-tabs">
                                <?php foreach ($this->identity()->langlist as $i => $lang) { ?>
                                    <li <?php echo ($i == 0) ? 'class="active"' : ''; ?>>
                                        <a href="#tab_<?php echo $lang[0]; ?>" data-toggle="tab"> <?php echo $lang[0].' - '.$this->translate($lang[1]); ?> </a>
                                    </li>
                                <?php } ?>
                            </ul>
                        <?php } ?>
                        <div <?php echo (count($this->identity()->langlist) > 1) ? 'class="tab-content"' : ''; ?>>
                            <?php foreach ($this->identity()->langlist as $i => $lang) { ?>
                                <?php
                                    if ($this->identity()->lang) {
                                        $arrsLang = array('tab' => $lang[0], 'data' => $this->item['translate'][$lang[0]], 'field' => $this->_field['validate']['translate']);
                                    }
                                ?>
                                <div class="tab-pane <?php echo ($i == 0) ? 'active' : ''; ?>" id="tab_<?php echo $lang[0]; ?>">
                                    <div class="row">
                                        <?php echo $this->partialLoop('partials/form-addedit.phtml', array(array('default' => $this->elements, 'lang' => $arrsLang, 'sortFields' => $this->sortFields))); ?>
                                    </div>
                                </div>
                            <?php } ?>
                        </div>
                    </div>
                </div>
                <div class="form-actions right">
                    <?php echo $buttons; ?>
                </div>
            </div>
        </div>
    </form>
    <?php if ($this->_params['id'] && $this->_field['comment']) { ?>
        <div class="profile-content">
            <div class="app-ticket app-ticket-details">
                <div class="portlet light ">
                    <div class="portlet-body">
                        <div class="row">
                            <div class="col-xs-12">
                                <div class="ticket-msg">
                                    <h3><i class="icon-note"></i> <?php echo $this->_field['comment']; ?></h3>
                                </div>
                                <div class="ticket-line"></div>
                                <form id="form-reply" class="form-group" action="" method="POST" enctype="multipart/form-data">
                                    <textarea name="comment" class="ticket-reply-msg" row="10"></textarea>
                                    <div class="text-right"><button class="btn uppercase btn-sm green-jungle" type="submit"><i class="icon-action-redo"></i> Bình luận</button></div>
                                </form>
                                <?php if($this->comment['list']) { ?>
                                    <div class="portlet light portlet-fit ht-portlet">
                                        <div class="portlet-body">
                                            <div class="timeline">
                                                <?php foreach ($this->comment['list'] as $x =>$value) {
                                                    $labelMain = $this->comment['status'][$value['status']];
                                                    $commentMain = '<span class="font-grey-cascade">'.$value['comment'].'</span>';
                                                    $icon = '';
                                                    if ($value['admin_id']) {
                                                        $icon = '<i class="icon-users font-green-haze"></i>';
                                                        if((file_exists(ROOT_PUBLIC.'/'.UPLOAD_IMAGES.date('Y/m',explode('-',$value['thumbnail'])[0]).'/100x100-'.$value['thumbnail'].WEBP_EXT) && is_file(ROOT_PUBLIC.'/'.UPLOAD_IMAGES.date('Y/m',explode('-',$value['thumbnail'])[0]).'/100x100-'.$value['thumbnail'].WEBP_EXT))) {
                                                            $icon = '<img src="'.PUBLIC_PATH.UPLOAD_IMAGES.date('Y/m',explode('-',$value['thumbnail'])[0]).'/100x100-'.$value['thumbnail'].'" alt="avatar">';
                                                        }

                                                        if($value['username'] == $this->_params['user']) {
                                                            $commentMain = '<span class="font-grey-cascade"><a href="javascript:;" ht-trigger="editable-comment" data-pk="'.$this->url('admincp',array('controller' => 'comment_tb','action' => 'change','id' => $value['id'])).'" data-original-title="Chỉnh sửa phản hồi">'.$value['comment'].'</a></span>';
                                                        }
                                                        $labelMain = '<span class="label label-sm label-info">Quản trị viên</span>';
                                                    }
                                                ?>
                                                    <div class="timeline-item">
                                                        <div class="timeline-body">
                                                            <div class="timeline-body-head clearfix">
                                                                <div class="timeline-body-head-caption">
                                                                    <span class="timeline-body-avatar">
                                                                        <?php echo $icon; ?>
                                                                    </span>
                                                                    <span class="timeline-body-title">
                                                                        <?php echo $value['fullname']; ?>
                                                                        <?php echo $labelMain; ?>
                                                                    </span>
                                                                    <span class="timeline-body-time font-grey-cascade"><?php echo date('H:i d/m/Y', strtotime($value['date_created'])); ?></span>
                                                                </div>
                                                            </div>
                                                            <div class="timeline-body-content">
                                                                <?php echo $commentMain; ?>
                                                            </div>
                                                            <div class="timeline-body-close">
                                                                <a href="javascript:;" class="btn red" onclick="_HTDelete.item('<?php echo $this->url('admincp',array('controller' => 'comment_tb','action' => 'delete','id' => $value['id'])); ?>');"><i class="fa fa-close"></i></a>
                                                            </div>
                                                            <?php if ($value['multi_image']) { ?>
                                                                <div class="timeline-body-image">
                                                                    <?php
                                                                        $value['multi_image'] = json_decode($value['multi_image'], true);
                                                                        $totalImg = count($value['multi_image']);
                                                                        foreach ($value['multi_image'] as $i => $vl_img) {
                                                                            $img = PUBLIC_PATH.UPLOAD_FILES.$vl_img;
                                                                            if ($i <= 2 || $totalImg <= 4) {
                                                                                echo '<a href="'.$img.'" class="fancybox-button" data-rel="fancybox-button-'.$x.'"><img src="'.$img.'" width="80"> </a>';
                                                                            } else if ($i == 3) {
                                                                                echo '<a href="'.$img.'" class="fancybox-button" data-rel="fancybox-button-'.$x.'"><img src="'.$img.'" width="80"><span>+'.($totalImg - 3).'</span></a>';
                                                                            }
                                                                        }
                                                                    ?>
                                                                </div>
                                                            <?php } ?>
                                                        </div>
                                                    </div>
                                                    <?php foreach ($value['child'] as $vl_child) { ?>
                                                        <?php
                                                            $icon = '<i class="icon-emoticon-smile font-green-haze"></i>';
                                                            $label = $vl_child['status'] != 1 ? '<span class="label label-sm label-danger">'.$this->comment['status'][$vl_child['status']].'</span>' : '';
                                                            $comment = '<span class="font-grey-cascade">'.$vl_child['comment'].'</span>';
                                                            if ($vl_child['admin_id']) {
                                                                $icon = '<i class="icon-users font-green-haze"></i>';

                                                                if((file_exists(ROOT_PUBLIC.'/'.UPLOAD_IMAGES.date('Y/m',explode('-',$vl_child['thumbnail'])[0]).'/100x100-'.$vl_child['thumbnail'].WEBP_EXT) && is_file(ROOT_PUBLIC.'/'.UPLOAD_IMAGES.date('Y/m',explode('-',$vl_child['thumbnail'])[0]).'/100x100-'.$vl_child['thumbnail'].WEBP_EXT))) {
                                                                    $icon = '<img src="'.PUBLIC_PATH.UPLOAD_IMAGES.date('Y/m',explode('-',$vl_child['thumbnail'])[0]).'/100x100-'.$vl_child['thumbnail'].'" alt="avatar">';
                                                                }

                                                                if($vl_child['username'] == $this->_params['user']) {
                                                                    $comment = '<span class="font-grey-cascade"><a href="javascript:;" ht-trigger="editable-comment" data-pk="'.$this->url('admincp',array('controller' => 'comment_tb','action' => 'change','id' => $vl_child['id'])).'" data-original-title="Chỉnh sửa phản hồi">'.$vl_child['comment'].'</a></span>';
                                                                }
                                                                $label = '<span class="label label-sm label-info">Quản trị viên</span>';
                                                            }
                                                        ?>
                                                        <div class="timeline-item">
                                                            <div class="timeline-badge">
                                                                <div class="timeline-icon"><?php echo $icon; ?></div>
                                                            </div>
                                                            <div class="timeline-body">
                                                                <div class="timeline-body-arrow"></div>
                                                                <div class="timeline-body-head clearfix">
                                                                    <div class="timeline-body-head-caption">
                                                                        <span class="timeline-body-title"><?php echo $vl_child['fullname']; ?> <?php echo $label; ?></span>
                                                                        <span class="timeline-body-time font-grey-cascade"><?php echo date('H:i d/m/Y', strtotime($vl_child['date_created'])); ?></span>
                                                                    </div>
                                                                </div>
                                                                <div class="timeline-body-content"><?php echo $comment; ?></div>
                                                                <div class="timeline-body-close">
                                                                    <a href="javascript:;" class="btn red" onclick="_HTDelete.item('<?php echo $this->url('admincp',array('controller' => 'comment_tb','action' => 'delete','id' => $vl_child['id'])); ?>');"><i class="fa fa-close"></i></a>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    <?php } ?>
                                                <?php } ?>
                                            </div>
                                        </div>
                                    </div>
                                <?php } ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php } ?>
</div>

<script>
    $(document).ready(function() {
        var rules = {}, checkForm = $.parseJSON('<?php echo json_encode($this->_params["checkForm"]); ?>');

        var field_required = Object.keys(checkForm.required);
        for (var i = 0; i < field_required.length; i++) {
            if (field_required[i].indexOf("thumbnail") > -1) continue;

            field_required[i] = (field_required[i] == 'cat_id' && '<?php echo $this->_field["cat_id"]; ?>' == 'checkbox') ? field_required[i]+'[]' : field_required[i];
            rules[field_required[i].replace(/\{(.*?)\}/g, "[$1]")] = {required: true};
        }

        if (checkForm.exists) {
            var field_exists = Object.keys(checkForm.exists);
            for (var j = 0; j < field_exists.length; j++) {
                rules[field_exists[j]] = rules[field_exists[j]] ? rules[field_exists[j]] : {};
                rules[field_exists[j]] = $.extend({}, rules[field_exists[j]], {exists: checkForm.exists[field_exists[j]]});
            }
        }

        FormValidation.submit('#form-add', {rules: rules});

        FormValidation.submit('#form-reply', {rules: {
            comment: {required: true}
        }});

        FormEditable.textarea('editable-comment', {
            name: 'comment',
            mode: 'inline',
            inputclass: 'width-100',
            innerCss: '.sdsd',
            containerClass: 'sdsdsdsd',
            rows: 3,
        });
        $('.editable-click').click(function() {
            if ($(this).hasClass('editable-open')) {
                $(this).next().css('display', 'block').find('form > .form-group').css('display', 'block');
            }
        });
    });
</script>