<div class="page-content">
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li><a href="<?php echo $this->url('admincp'); ?>"><?php echo $this->translate("Trang chủ"); ?></a><i class="fa fa-circle"></i></li>
            <li><span><?php echo $this->_params['title']; ?></span></li>
        </ul>
        <?php if ($this->identity()->supper) { ?>
            <div class="pull-right">
                <a href="<?php echo $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'codefield','root_id' => $this->_params['root_id'])); ?>" class="btn green pull-right"><i class="fa fa-cogs"></i> Cấu hình dữ liệu</a>
                <a href="<?php echo $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'codevalidate','root_id' => $this->_params['root_id'])); ?>" class="btn green pull-right"><i class="fa fa-cogs"></i> Định nghĩa dữ liệu</a>
                <a href="<?php echo $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'sortfield','root_id' => $this->_params['root_id']), array('query' => array('type' => 'detail'))); ?>" class="btn green pull-right"><i class="fa fa-cogs"></i> Sắp xếp dữ liệu</a>
            </div>
        <?php } ?>
    </div>
    <div class="portlet box blue margin-bottom-0">
        <div class="portlet-title">
            <div class="caption"><?php echo $this->translate("Danh sách"); ?> </div>
            <div class="actions btn-group">
                <?php
                    if ($this->_field['up_date'] && $this->_params['permission']['other']) {
                        echo '<a href="javascript:;" class="btn red" onclick="_HTChange.dateup(\''.$this->linkChange.'\');"><i class="fa fa-refresh "></i> UP</a>';
                    }
                    if ($this->_field['transfer_cate'] && $this->_params['permission']['transfer_cate']) {
                        echo '<a href="javascript:;" class="btn grey-salsa" onclick="_HTChange.cate();"><i class="fa fa-exchange"></i> '.$this->translate("Chuyển danh mục").'</a>';
                    }
                    if ($this->_field['add'] || $this->_field['delete']) {
                        if ($this->_field['add'] && $this->_params['permission']['add']) {
                            echo '<a href="'.$this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'field','root_id' => $this->_params['root_id'])).'" class="btn yellow"><i class="fa fa-plus-square-o"></i> '.$this->translate("Thêm").'</a>';
                        }
                        if($this->_field['delete']) {
                            if ($this->_params['permission']['delete'] || $this->_params['permission']['d-status']) {
                                echo '<a href="javascript:;" class="btn red" onclick="_HTDelete.rows(\''.$this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'delete')).'\',\'/root_id='.$this->_params['root_id'].'\');"><i class="fa fa-trash-o"></i> '.$this->translate("Xóa nhiều").'</a>';
                            }
                        }
                    }
                ?>
            </div>
        </div>
        <div class="portlet-body">
            <?php if ($this->_field['cat_id'] > 0 || $this->_field['status'] || $this->_field['date_published']) { ?>
                <div class="ht-filter">
                    <form id="form-filter" action="" method="post" accept-charset="utf-8">
                        <?php if ($this->_field['cat_id'] > 0) { ?>
                            <div class="ht-filter__category">
                                <div class="input-group input-group-sm select2-bootstrap-prepend">
                                    <span class="input-group-btn">
                                        <button class="btn btn-default" type="button" data-select2-open="ht-open-boxCate"><?php echo $this->translate("Danh mục"); ?></button>
                                    </span>
                                    <select name="cat_id" id="ht-open-boxCate" class="form-control select2" onchange="_HTHelper.submit(this);">
                                        <option value="<?php echo $this->_params['root_id']; ?>"><?php echo $this->translate("Tất cả"); ?></option>
                                        <?php foreach ($this->filter as $value) { ?>
                                            <option value="<?php echo $value['id']; ?>" <?php echo ($value['id'] == $this->query['cat_id']) ? 'selected' : ''; ?> class="level<?php echo $value['level']; ?>"><?php echo $value['name']; ?></option>
                                        <?php } ?>
                                    </select>
                                </div>
                            </div>
                        <?php } ?>
                        <?php if ($this->_field['status'] || $this->_field['date_published']) { ?>
                            <div class="ht-filter__status">
                                <div class="input-group input-group-sm select2-bootstrap-prepend">
                                    <select id="ht-open-status" name="status" class="form-control select2 select2-not-search" onchange="_HTHelper.submit(this);">
                                        <option value="all"><?php echo $this->translate("Tất cả"); ?></option>
                                        <?php
                                            foreach ($this->status as $status) {
                                                echo '<option value="'.$status['value'].'" '.(($status['value'] == $this->query['status']) ? 'selected' : '').'>'.$status['text'].'</option>';
                                            }
                                        ?>
                                    </select>
                                    <span class="input-group-btn">
                                        <button class="btn btn-default" type="button" data-select2-open="ht-open-status"><?php echo $this->translate("Trạng thái"); ?></button>
                                    </span>
                                </div>
                            </div>
                        <?php } ?>
                    </form>
                </div>
            <?php } ?>

            <table id="datatable-news" class="table table-striped table-bordered table-hover table-checkable action-column <?php echo (($this->_field['colvis']) ? 'colvis-column' : ''); ?>">
                <?php
                    $columns = array();
                    foreach ($this->columns as $column) {
                        if ($column['colvis'] != true) {
                            $columns[] = array(
                                'name' => $column['name'],
                                'data' => $column['data'],
                                'title' => $column['title'],
                                'class' => $column['class'] ?? 'min-width-100',
                                'orderable' => $column['orderable'] ?? false,
                                'searchable' => $column['searchable'] ?? false,
                            );
                        }
                    }
                ?>
            </table>
        </div>
    </div>
    <?php if ($this->_field['cat_id'] > 0) { ?>
        <div id="change-cate" class="modal fade" tabindex="-1" role="basic" data-backdrop="static" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header"><h4 class="modal-title text-center text-uppercase"><?php echo $this->translate("Chuyển danh mục"); ?></h4></div>
                    <div class="modal-body">
                        <div class="input-group select2-bootstrap-prepend">
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="button" data-select2-open="ht-open-changeCate"><?php echo $this->translate("Danh mục"); ?></button>
                            </span>
                            <select name="cat_id" id="ht-open-changeCate" class="form-control select2">
                                <option></option>
                                <?php foreach ($this->filter as $value) { ?>
                                    <option value="<?php echo $value['id']; ?>" class="level<?php echo $value['level']; ?>"><?php echo $value['name']; ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <div class="text-center">
                            <button type="button" class="btn salsa" onclick="_HTChange.cate('<?php echo $this->linkChange; ?>');"><i class="fa fa-exchange"></i> <?php echo $this->translate("Chuyển danh mục"); ?></button>
                            <button type="button" class="btn red" data-dismiss="modal"><i class="fa fa-ban"></i> <?php echo $this->translate("Hủy"); ?></button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php } ?>
</div>
<script>
    $(document).ready(function() {
        var tableId = '#datatable-news';

        TableDatatables.init({
            'tableId': tableId,
            'processing': false,
            'serverSide': true,
            'select': false,
            'columns': $.parseJSON('<?php echo json_encode($columns); ?>'),
            'customize': {
                colvis: '<?php echo $this->_field['colvis'] ? $this->url('admincp', array('controller' => $this->_params['__CONTROLLER__'],'action' => 'sortfield','root_id' => $this->_params['root_id']), array('query' => array('type' => 'list'))) : ''; ?>',
            },
            'ajax': {
                'type': 'POST',
                'url': "<?php echo $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'list', 'root_id' => $this->_params['root_id'])).($_SERVER['QUERY_STRING'] ? '?'.$_SERVER['QUERY_STRING'] : ''); ?>"
            },
            drawCallback: function( settings ) {
                var status = $.parseJSON('<?php echo json_encode($this->status); ?>');
                FormEditable.group('editable-status', {
                    name: 'status',
                    responseText: (status || []).map(item => ({...item, text: item.value == 1 ? 'Xuất bản' : item.text})),
                });
            }
        });

        // Custom display editable
        $('body').on('click', '.editable-click', function() {
            if ($(this).hasClass('editable-open')) {
                $("#datatable-news .editable-open").not(this).click();
                var tagARect = this.getBoundingClientRect();
                var $this = $(this);
                setTimeout(function() {
                    var domRect = $this.siblings('.popover')[0].getBoundingClientRect();
                    $this.siblings('.popover').removeClass('top');
                    $this.siblings('.popover').addClass('bottom');
                    $this.siblings('.popover').css({
                        position: 'fixed',
                        top: (domRect.top  - (tagARect.height/2)) + 'px',
                        left: domRect.left + 'px',
                    });
                }, 100);
            }
        })
        document.addEventListener("scroll", function(){
            $("#datatable-news .editable-open").click();
        });
    });
</script>