<div class="page-content">
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li><a href="<?php echo $this->url('admincp'); ?>"><?php echo $this->translate("Trang chủ"); ?></a><i class="fa fa-circle"></i></li>
            <li><span><?php echo $this->_params['title']; ?></span></li>
        </ul>
    </div>
    <div class="portlet box blue margin-bottom-0">
        <div class="portlet-title">
            <div class="caption"><?php echo $this->translate("Danh sách"); ?> </div>
            <div class="actions">
                <a href="<?php echo $this->url('admincp',array('controller' => 'menu_code_tb','action' => 'field')); ?>" class="btn yellow"><i class="fa fa-plus-square-o"></i> <?php echo $this->translate("Thêm"); ?></a>
            </div>
        </div>
        <div class="portlet-body">
            <table id="datatable-default" class="table table-striped table-bordered table-hover table-checkable">
                <thead>
                    <tr>
                        <th class="table-checkall"> ID </th>
                        <th class="table-func"> Trạng thái </th>
                        <th> Tên menu </th>
                        <th class="table-sort text-center"> Sắp xếp </th>
                        <th class="nosort nosearch table-sort"> </th>
                    </tr>
                </thead>
                </tbody>
                    <?php foreach ($this->list as $value) { ?>
                        <?php
                            $linkChange = $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'change','id' => $value['id'],'root_id' => $this->_params['root_id']));
                            $linkDelete = $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'delete','id' => $value['id']));
                            $onclick = array('_HTChange.status(this, \'switch\', '.htmlspecialchars(json_encode(array('url' => $linkChange), JSON_UNESCAPED_SLASHES)).')', '_HTChange.permitAdmin(\''.$this->url('admincp',array('controller' => 'admin_role_tb','action' => 'field','id' => 1,'root_id' => 24), array('query' => array('permitAdmin' => 1), 'strlen')).'\')');
                        ?>
                        <tr class="odd gradeX">
                            <td> <?php echo $value['id']; ?> </td>
                            <td class="text-center">
                                <label><input type="checkbox" name="display" class="make-switch" data-on-text="Mở" data-off-text="Tắt" <?php echo ($value['parent'] == 0) ? 'data-size="small"' :'data-size="mini"'; ?> <?php echo ($value['display']) ? 'checked' : ''; ?> <?php echo ($value['default']) ? 'disabled' : ''; ?> onchange="<?php echo implode(',', $onclick); ?>" value="<?php echo $value['display']; ?>"></label>
                            </td>
                            <td>
                                <div style="display: flex;">
                                    <a href="<?php echo $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'field','id' => $value['id'])); ?>" class="<?php echo ($value['parent'] == 0) ? 'level1' : 'level2';?>" style="margin-right: auto;"><?php echo $value['name']; ?></a>
                                </div>
                            </td>
                            <td>
                                <input type="text" name="sort" class="form-control text-center input-sm <?php echo ($value['parent'] == 0) ? 'bold' : '';?>" onkeydown="_HTChange.sort(this, '<?php echo $linkChange; ?>');" value="<?php echo $value['sort']; ?>">
                            </td>
                            <td class="text-center">
                                <?php if ($value['fixed'] == 0) { echo '<a href="javascript:;" class="btn btn-sm red" onclick="_HTDelete.item(\''.$linkDelete.'\');">Xóa</a>'; } ?>
                            </td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        TableDatatables.init({ destroy: true,  dom: '', ordering: false, pageLength: -1 });
    });
</script>