<div class="logo"><img src="<?php echo BE_TEMPLATE.'/layouts/layout/img/logo.png'; ?>" alt="logo.png" /></div>
<div class="content">
    <h1>BLOCKED</h1>
    <p><?php echo $this->translate("Bạn nhập sai").' '.FAIL_NUMBER.' '.$this->translate("lần"); ?>.</p>
    <p><?php echo $this->translate("Vui lòng đợi sau"); ?> <span style="color: red;" id="time"></span> <?php echo $this->translate("giây để đăng nhập lại"); ?>.</p>
</div>
<style type="text/css" media="screen">
    .login .content {
        width: 525px;
    }
    .content h1 {
        color: #fff;
        font-size: 78px;
        line-height: 1;
        text-align: center;
        margin-bottom: 35px;
        font-weight: 300;
        text-stroke: 1px transparent;
        display: block;
        text-shadow: 0 1px 0 #ccc, 0 2px 0 #c9c9c9, 0 3px 0 #bbb, 0 4px 0 #b9b9b9, 0 5px 0 #aaa, 0 6px 1px rgba(0, 0, 0, .1), 0 0 5px rgba(0, 0, 0, .1), 0 1px 3px rgba(0, 0, 0, .3), 0 3px 5px rgba(0, 0, 0, .2), 0 5px 10px rgba(0, 0, 0, .25), 0 10px 10px rgba(0, 0, 0, .2), 0 20px 20px rgba(0, 0, 0, .15);

    }
    .content p {
        text-align: center;
        margin: 5px 0;
        font-size: 20px;
        text-transform: uppercase;
    }
</style>
<script language="javascript">

    var m, s;
    s = Math.floor('<?php echo $this->lock_expire_real; ?>');
    m = Math.floor(s / 60);
    s = s % 60;
    m = m % 60;

    var timeout = null;

    function start()
    {
        // Nếu số giây = -1 tức là đã chạy ngược hết số giây, lúc này:
        //  - giảm số phút xuống 1 đơn vị
        //  - thiết lập số giây lại 59
        if (s === -1){
            m -= 1;
            s = 59;
        }
        // Nếu số phú = -1 tức là đã hết giờ, lúc này:
        //  - Dừng chương trình
        if (m == -1){
            clearTimeout(timeout);
            window.location.href = "<?php echo $this->url('admincp',array('controller' => 'login.html')); ?>";
            return false;
        }
        // Hiển thị đồng hồ
        document.getElementById('time').innerText = m.toString()+':'+s.toString();
        // Giảm giây và gọi lại
        timeout = setTimeout(function(){
            s--;
            start();
        }, 1000);
    }
    start();
</script>