<div class="page-content">
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li><a href="<?php echo $this->url('admincp'); ?>"><?php echo $this->translate("Trang chủ"); ?></a><i class="fa fa-circle"></i></li>
            <li><span><?php echo $this->_params['title']; ?></span></li>
        </ul>
    </div>
    <div class="portlet box blue margin-bottom-0">
        <div class="portlet-title">
            <div class="caption"><?php echo $this->translate("Danh sách"); ?> </div>
            <div class="actions">
                <a href="<?php echo $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'field','root_id' => $this->_params['root_id'])); ?>" class="btn yellow"><i class="fa fa-plus-square-o"></i> <?php echo $this->translate("Thêm mới"); ?></a>
                <a href="javascript:;" class="btn red" onclick="_HTDelete.rows('<?php echo $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'delete')); ?>','/root_id=<?php echo $this->_params['root_id']; ?>');"><i class="fa fa-trash-o"></i> <?php echo $this->translate("Xóa nhiều"); ?></a>
            </div>
        </div>
        <div class="portlet-body">
            <div class="ht-filter">
                <form id="form-filter" action="" method="post" accept-charset="utf-8">
                    <div class="ht-filter__status">
                        <div class="input-group input-group-sm select2-bootstrap-prepend">
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="button" data-select2-open="ht-open-status"><?php echo $this->translate("Trạng thái"); ?></button>
                            </span>
                            <select id="ht-open-status" name="status" class="form-control select2 select2-not-search" onchange="_HTHelper.submit(this);">
                                <option value="all"><?php echo $this->translate("Tất cả"); ?></option>
                                <?php foreach ($this->status as $value) { ?>
                                    <option value="<?php echo $value['value']; ?>" <?php echo ($value['value'] == $this->query['status']) ? 'selected' : ''; ?>><?php echo $value['text']; ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                </form>
            </div>
            <table id="datatable-default" class="table table-striped table-bordered table-hover table-checkable excel-column">
                <thead>
                    <tr>
                        <th class="nosort noexcel table-checkall">
                            <label class="mt-checkbox mt-checkbox-outline">
                                <input type="checkbox" class="group-checkable" data-set=".ht-checkall-rows" />
                                <span></span>
                            </label>
                        </th>
                        <th class="table-checkall"> ID </th>
                        <th class="nosort text-center table-thumbnail">Ảnh</th>
                        <th> <?php echo $this->translate("Thành viên"); ?> </th>
                        <th> Email </th>
                        <th class="text-center"> <?php echo $this->translate("Điện thoại"); ?> </th>
                        <?php if ($this->_field['hasOrder']) { ?>
                            <th class="text-center"> <?php echo $this->translate("Số đơn hàng"); ?> </th>
                        <?php } ?>
                        <th class="text-center"> <?php echo $this->translate("Trạng thái"); ?> </th>
                        <th class="nosort noexcel nosearch table-func"> <?php echo $this->translate("Chức năng"); ?> </th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->list as $value) { ?>
                        <?php
                            $linkDetail = $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => $this->_field['hasOrder'] ? 'view' : 'field','id' => $value['id'],'root_id' => $this->_params['root_id']));
                            $linkChange = $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'change','id' => $value['id'], 'root_id' => $this->_params['root_id']));
                        ?>
                        <tr class="odd gradeX">
                            <td>
                                <label class="mt-checkbox mt-checkbox-outline">
                                    <input type="checkbox" class="ht-checkall-rows" value="<?php echo $value['id']; ?>" />
                                    <span></span>
                                </label>
                            </td>
                            <td><?php echo $value['id']; ?></td>
                            <?php
                                $thumbnail = UPLOAD_IMAGES.date('Y/m',explode('-',$value['thumbnail'])[0]).'/autox30-'.$value['thumbnail'];
                                $thumbnail = ($value['thumbnail'] && file_exists(ROOT_PUBLIC.'/'.$thumbnail)) ? PUBLIC_PATH.$thumbnail : BE_TEMPLATE.'/layouts/layout/img/noimage.png';
                                echo '<td class="text-center"><img src="'.$thumbnail.'" /></td>';
                            ?>
                            <td><a href="<?php echo $linkDetail ; ?>"><?php echo $value['fullname']; ?></a></td>
                            <td><?php echo $value['email']; ?></td>
                            <td class="text-center"><?php echo $value['phone']; ?></td>
                            <?php if ($this->_field['hasOrder']) { ?>
                                <td class="text-center"><?php echo $value['count']; ?></td>
                            <?php } ?>
                            <td class="text-center">
                                <?php echo ($value['status'] == 0) ? $this->translate("Inactive") : $this->translate("Active"); ?>
                            </td>
                            <td>
                                <div class="text-center">
                                    <div class="btn-group btn-group-sm btn-group-solid">
                                        <a href="<?php echo $linkDetail ; ?>" class="btn blue"><?php echo $this->translate($this->_field['hasOrder'] ? "Xem" : "Sửa"); ?></a>
                                        <a href="javascript:;" class="btn red" onclick="_HTDelete.item('<?php echo $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'delete','id' => $value['id'])); ?>');"><?php echo $this->translate("Xóa"); ?></a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
