<div class="page-content">
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li><a href="<?php echo $this->url('admincp'); ?>"><?php echo $this->translate("Trang chủ"); ?></a><i class="fa fa-circle"></i></li>
            <li><span><?php echo $this->_params['title']; ?></span></li>
        </ul>
    </div>
    <div class="portlet box blue margin-bottom-0">
        <div class="portlet-title">
            <div class="caption"><?php echo $this->translate("Danh sách"); ?> </div>
            <?php if ($this->identity()->supper) { ?>
                <div class="actions">
                    <a href="<?php echo $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'field','root_id' => $this->_params['root_id'])); ?>" class="btn yellow"><i class="fa fa-plus-square-o"></i> <?php echo $this->translate("Thêm"); ?></a>
                </div>
            <?php } ?>
        </div>
        <div class="portlet-body">
            <table id="datatable-default" class="table table-striped table-bordered table-hover table-checkable">
                <thead>
                    <tr>
                    <?php
                        echo '<th class="table-checkall"> ID </th>';
                        echo '<th>'.$this->translate($this->_field['name']).'</th>';
                        if ($this->identity()->supper) {
                            echo '<th>'.$this->translate($this->_field['name']).' (default)</th>';
                            echo '<th class="nosearch table-show">'.$this->translate("Hiển thị").'</th>';
                            echo '<th class="nosort nosearch table-func">'.$this->translate("Chức năng").'</th>';
                        } else {
                            echo '<th class="nosearch table-show">'.$this->translate("Hiển thị").'</th>';
                        }
                    ?>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->list as $value) { ?>
                        <?php
                            $linkField = $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'field','id' => $value['id'],'root_id' => $this->_params['root_id']));
                            $linkDelete = (in_array($value['id'], array(1,2,3,4,5,6,7,8))) ? '' : '<a href="javascript:;" class="btn red" onclick="_HTDelete.item(\''.$this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'delete','id' => $value['id'],'root_id' => $this->_params['root_id'])).'\');">'.$this->translate("Xóa").'</a>';
                        ?>
                        <tr class="odd gradeX">
                        <?php
                            echo '<td>'.$value['id'].'</td>';
                            echo '<td><a href="'.$linkField.'">'.$value['name'].'</a></td>';
                            if ($this->identity()->supper) {
                                echo '<td><a href="'.$linkField.'?style=default">'.$value['name'].'</a></td>';
                                echo '<td class="text-center"><label class="mt-checkbox mt-checkbox-outline"><input type="checkbox" name="display" value="'.$value['display'].'" onclick="_HTChange.status(this, \'switch\', '.htmlspecialchars(json_encode(array('url' => $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'change','id' => $value['id']))), JSON_UNESCAPED_SLASHES)).');" '.($value['display'] ? 'checked' : '').' /><span class="text-hide">'.$value['display'].'</span></label></td>';
                                echo '<td><div class="text-center"><div class="btn-group btn-group-sm btn-group-solid">'.$linkDelete.'</div></div></td>';
                            } else {
                                echo '<td class="text-center"><label class="mt-checkbox mt-checkbox-outline"><input type="checkbox" name="display" value="'.$value['display'].'" onclick="_HTChange.status(this, \'switch\', '.htmlspecialchars(json_encode(array('url' => $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'change','id' => $value['id']))), JSON_UNESCAPED_SLASHES)).');" '.($value['display'] ? 'checked' : '').' /><span class="text-hide">'.$value['display'].'</span></label></td>';
                            }
                        ?>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>