<div class="page-content">
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li><a href="<?php echo $this->url('admincp'); ?>"><?php echo $this->translate("Trang chủ"); ?></a><i class="fa fa-circle"></i></li>
            <li><a href="<?php echo $this->linkList; ?>"><?php echo explode('/', $this->_params['title'])[0]; ?></a><i class="fa fa-circle"></i></li>
            <li><span><?php echo explode('/', $this->_params['title'])[1]; ?></span></li>
        </ul>
    </div>
    <form id="form-add" action="" method="POST" enctype="multipart/form-data" onchange="setIsChangeValue();" onkeydown="setIsChangeValue();">
        <div class="portlet box blue margin-bottom-0">
            <div class="portlet-title">
                <div class="caption"><?php echo $this->translate("Thông tin chi tiết"); ?> </div>
                <div class="actions">
                    <?php if (!$this->_params['id'] && !$this->order_id) { ?>
                        <label class="mt-checkbox mt-checkbox-right">
                            <input type="checkbox" value="checked" name="continue" ht-trigger="add-continue" <?php echo $this->continue; ?>/>
                            <span></span><?php echo $this->translate("Thêm mới khác"); ?>
                        </label>
                    <?php } ?>
                    <button type="submit" onclick="_HTSend.form(this)" class="btn btn-sm green-jungle"><i class="fa fa-check-square-o"></i> <?php echo $this->translate("Lưu"); ?></button>
                    <a href="<?php echo $this->linkList; ?>" class="btn btn-sm red"><i class="fa fa-share"></i> <?php echo $this->translate("Thoát"); ?></a>
                </div>
            </div>
            <div class="portlet-body form form-help-freeze">
                <div class="form-body">
                    <?php if ($this->order_id) { ?>
                        <div class="alert alert-info display-block">
                            <p><?php echo explode('/', $this->_params['title'])[1].' '.explode('/', $this->_params['title'])[0]; ?> cho đơn hàng <b>#<?php echo $this->order_id; ?></b></p>
                        </div>
                    <?php } ?>
                    <?php if ($this->error) { ?>
                        <div class="alert alert-danger display-block">
                            <button class="close" data-close="alert"></button>
                            <?php foreach ($this->error as $error) { echo '<p>'.$error.'</p>'; } ?>
                        </div>
                    <?php } ?>
                    <div class="row">
                        <?php echo $this->partialLoop('partials/form-addedit.phtml', array(array('default' => $this->elements, 'currency' => $this->_field['unit']))); ?>
                    </div>
                </div>
                <div class="form-actions right">
                    <?php if (!$this->_params['id'] && !$this->order_id) { ?>
                        <label class="mt-checkbox mt-checkbox-outline mt-checkbox-right">
                            <input type="checkbox" value="checked" name="continue" ht-trigger="add-continue" <?php echo $this->continue; ?>/>
                            <span></span><?php echo $this->translate("Thêm mới khác"); ?>
                        </label>
                    <?php } ?>
                    <button type="submit" onclick="_HTSend.form(this)" class="btn btn-sm green-jungle"><i class="fa fa-check-square-o"></i> <?php echo $this->translate("Lưu"); ?></button>
                    <a href="<?php echo $this->linkList; ?>" class="btn btn-sm red"><i class="fa fa-share"></i> <?php echo $this->translate("Thoát"); ?></a>
                </div>
            </div>
        </div>
    </form>
</div>
<script>
    $(document).ready(function() {
        var rules = {}, checkForm = $.parseJSON('<?php echo json_encode($this->_params["checkForm"]); ?>');
        var unit = '<?php echo $this->_field['unit'] ?? 'vnd'; ?>';

        if (checkForm.required) {
            var field_required = Object.keys(checkForm.required);
            for (var i = 0; i < field_required.length; i++) {
                field_required[i] = (field_required[i] == 'cat_id' && '<?php echo $this->_field["cat_id"]; ?>' == 'checkbox') ? field_required[i]+'[]' : field_required[i];
                rules[field_required[i].replace(/\{(.*?)\}/g, "[$1]")] = {required: true};
            }
        }

        if (checkForm.exists) {
            var field_exists = Object.keys(checkForm.exists);
            for (var j = 0; j < field_exists.length; j++) {
                rules[field_exists[j]] = rules[field_exists[j]] ? Object.assign(rules[field_exists[j]], {exists: checkForm.exists[field_exists[j]]}) : {exists: checkForm.exists[field_exists[j]]};
            }
        }

        if (checkForm.url) {
            var field_url = Object.keys(checkForm.url);
            for (var k = 0; k < field_url.length; k++) {
                rules[field_url[k]] = rules[field_url[k]] ? Object.assign(rules[field_url[k]], {url: true}) : {url: true};
            }
        }

        if ($('input[name="discount_type"]:checked').val() == 1) {
            rules.discount_value = rules.discount_value ? Object.assign(rules.discount_value, {range: [1, 100]}) : {range: [1, 100]};
        }

        if ($('input[name="discount_type"]:checked').val() == 2) {
            $('#discount_value').attr('data-unit', unit);
        }

        FormValidation.submit('#form-add', {
            rules: {
                ...rules,
                sku: {
                    ...rules.sku,
                    maxlength: 20,
                    regex: /^[A-Za-z0-9]+$/,
                }
            },
            messages: {
                sku: {
                    regex: 'Chỉ được nhập với ký tự \"A-Za-z0-9\"'
                }
            }
        });

        $('input[name="discount_type"]').click(function(e) {
            if ($(this).val() == 1) {
                var value = Math.floor($('#discount_value').val());
                $('#discount_value').rules('add', {range: [1,100]});
                $('#discount_value').val(parseInt(value) > 100 ? '' : value);
                $('#discount_value').removeAttr('data-unit');
            } else {
                $('#discount_value').rules('remove', 'range');
                $('#discount_value').siblings('cite').remove();
                $('#discount_value').closest('.has-error').removeClass('has-error');
                $('#discount_value').attr('data-unit', unit);
            }
        });
    });
</script>