<div class="page-content">
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li><a href="<?php echo $this->url('admincp'); ?>"><?php echo $this->translate("Trang chủ"); ?></a><i class="fa fa-circle"></i></li>
            <li><span><?php echo $this->_params['title']; ?></span></li>
        </ul>
        <?php if ($this->identity()->supper) { ?>
            <a href="<?php echo $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'codefield','root_id' => $this->_params['root_id'])); ?>" class="btn green pull-right"><i class="fa fa-cogs"></i> Cấu hình dữ liệu</a>
        <?php } ?>
    </div>
    <div class="portlet box blue margin-bottom-0">
        <div class="portlet-title">
            <div class="caption"><?php echo $this->translate("Danh sách"); ?> </div>
            <div class="actions">
                <?php if ($this->_field['add']) { ?>
                    <a href="<?php echo $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'field','root_id' => $this->_params['root_id'])); ?>" class="btn yellow"><i class="fa fa-plus-square-o"></i> <?php echo $this->translate("Thêm"); ?></a>
                <?php } ?>
            </div>
        </div>
        <div class="portlet-body">
            <div class="tabbable-custom ">
                <ul class="nav nav-tabs ">
                    <?php foreach ($this->status as $id => $value) {
                        echo '<li '.($this->active == $id ? 'class="active"' : '').'><a href="'.$value['link'].'"> '.$value['name'].' </a></li>';
                    } ?>
                </ul>
                <div class="tab-content active">
                    <table id="datatable-default" class="table table-striped table-bordered table-hover table-checkable">
                        <thead>
                            <tr>
                            <?php
                                echo '<th class="table-checkall"> ID </th>';
                                echo '<th>'.$this->translate($this->_field['sku']).'</th>';
                                echo '<th>'.$this->translate($this->_field['discount_value']).'</th>';
                                // echo '<th>'.$this->translate("Áp dụng cho").'</th>';
                                if ($this->_field['expired_number']) {
                                    echo '<th>'.$this->translate($this->_field['expired_number']).'</th>';
                                }
                                if ($this->_field['expired_date']) {
                                    echo '<th>'.$this->translate($this->_field['expired_date']).'</th>';
                                }
                                if ($this->_field['auto'] && $this->active == 1) {
                                    echo '<th class="nosearch table-show">'.$this->translate($this->_field['auto']).'</th>';
                                }
                                if ($this->_field['add']) {
                                    echo '<th class="nosort nosearch table-func '.($this->_field['copy'] ? 'copy' : '').'">'.$this->translate("Chức năng").'</th>';
                                }
                            ?>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($this->list as $value) { ?>
                                <?php
                                    $linkField = $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'field','id' => $value['id'],'root_id' => $this->_params['root_id']), array('query' => array('status' => $this->active), 'strlen'));
                                    $linkChange = $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'change','id' => $value['id']));
                                    $linkDelete = $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'delete','id' => $value['id'],'root_id' => $this->_params['root_id']));
                                    $value['allowed_type'] = $this->_field['allowed'][array_search($value['allowed_type'], array_column($this->_field['allowed'], 'id'))]['name'];
                                    // $allowed_type =
                                ?>
                                <tr class="odd gradeX">
                                <?php
                                    echo '<td>'.$value['id'].'</td>';
                                    echo '<td><a href="'.$linkField.'">'.$value['sku'].'</a></td>';
                                    echo '<td>'.$this->formatCurrency($value['discount_value']).($value['discount_type'] == 1 ? '%' : 'đ').'</td>';
                                    //echo '<td>'.$value['allowed_type'].'</td>';
                                    if ($this->_field['expired_number']) {
                                        echo '<td>'.$value['remain'].' / '.($value['expired_number'] > 0 ? $value['expired_number'] : '~').'</td>';
                                    }
                                    if ($this->_field['expired_date']) {
                                        echo '<td>'.($value['expired_date'] ?? '-').'</td>';
                                    }
                                    if ($this->_field['auto'] && $this->active == 1) {
                                        echo '<td class="text-center"><label class="mt-radio mt-radio-outline"><input type="radio" name="auto" value="'.$value['auto'].'" onclick="_HTChange.status(this, \'discount\', '.htmlspecialchars(json_encode(array('url' => $linkChange), JSON_UNESCAPED_SLASHES)).');" '.($value['auto'] ? 'checked' : '').' /><span class="text-hide">'.$value['auto'].'</span></label></td>';
                                    }
                                    if ($this->_field['add']) {
                                        echo '<td><div class="text-center"><div class="btn-group btn-group-sm btn-group-solid">'.($this->_field['copy'] ? '<a href="'.$linkField.'?action=copy" class="btn yellow">Copy</a>' : '').'<a href="'.$linkField.'" class="btn blue">'.$this->translate("Sửa").'</a><a href="javascript:;" class="btn red" onclick="_HTDelete.item(\''.$linkDelete.'\', true);">'.$this->translate("Xóa").'</a></div></div></td>';
                                    }
                                ?>
                                </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>