<div class="page-content">
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li><a href="<?php echo $this->url('admincp'); ?>"><?php echo $this->translate("Trang chủ"); ?></a><i class="fa fa-circle"></i></li>
            <li><span><?php echo $this->_params['title']; ?></span></li>
        </ul>
        <?php if ($this->identity()->supper) { ?>
            <a href="<?php echo $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'codefield','root_id' => $this->_params['root_id'])); ?>" class="btn green pull-right"><i class="fa fa-cogs"></i> Cấu hình dữ liệu</a>
        <?php } ?>
    </div>
    <div class="portlet box blue margin-bottom-0">
        <div class="portlet-title">
            <div class="caption"><?php echo $this->translate("Danh sách"); ?> </div>
            <div class="actions">
                <?php if ($this->_field['add']) { ?>
                    <a href="<?php echo $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'field','root_id' => $this->_params['root_id'])); ?>" class="btn yellow"><i class="fa fa-plus-square-o"></i> <?php echo $this->translate("Thêm"); ?></a>
                <?php } if ($this->_field['delete']) { ?>
                    <a href="javascript:;" class="btn red" onclick="_HTDelete.rows('<?php echo $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'delete')); ?>','/root_id=<?php echo $this->_params['root_id']; ?>');"><i class="fa fa-trash-o"></i> <?php echo $this->translate("Xóa nhiều"); ?></a>
                <?php } ?>
            </div>
        </div>
        <div class="portlet-body">
            <table id="datatable-default" class="table table-striped table-bordered table-hover table-checkable">
                <thead>
                    <tr>
                    <?php
                        echo '<th class="nosort nosearch table-checkall"><label class="mt-checkbox mt-checkbox-outline"><input type="checkbox" class="group-checkable" data-set=".ht-checkall-rows" /><span></span></label></th>';
                        echo '<th class="table-checkall"> ID </th>';
                        echo '<th>'.$this->translate($this->_field['url_old']).'</th>';
                        echo '<th>'.$this->translate($this->_field['url_new']).'</th>';
                        echo '<th class="nosort nosearch table-func copy">'.$this->translate("Chức năng").'</th>';
                    ?>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->list as $value) { ?>
                        <?php
                            $linkField = $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'field','id' => $value['id'],'root_id' => $this->_params['root_id']));
                            $linkDelete = $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'delete','id' => $value['id'],'root_id' => $this->_params['root_id']));
                        ?>
                        <tr class="odd gradeX">
                        <?php
                            echo '<td><label class="mt-checkbox mt-checkbox-outline"><input type="checkbox" class="ht-checkall-rows" value="'.$value['id'].'" /><span></span></label></td>';
                            echo '<td>'.$value['id'].'</td>';
                            echo '<td>'.$value['url_old'].'</td>';
                            echo '<td style="word-break: break-all;">'.$value['url_new'].'</td>';
                            echo '<td style="word-break: break-all;"><div class="text-center"><div class="btn-group btn-group-sm btn-group-solid">';
                            echo '<a href="'.URL.substr($value['url_old'], 1).'" target="blank" class="btn yellow popovers" data-container="body" data-trigger="hover" data-placement="top" data-content="Xóa cache trình duyệt trước khi kiểm tra.">'.$this->translate("Kiểm tra").'</a>';
                            if ($this->_field['add'] || $this->_field['delete']) {
                                echo $this->_field['add'] ? '<a href="'.$linkField.'" class="btn blue">'.$this->translate("Sửa").'</a>' : '';
                                echo $this->_field['delete'] ? '<a href="javascript:;" class="btn red" onclick="_HTDelete.item(\''.$linkDelete.'\', true);">'.$this->translate("Xóa").'</a>' : '';
                            }
                            echo '</div></div></td>';
                        ?>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>