<?php
	switch ($this->params['type']) {
		case 'news21X':
			echo $this->block1(array('list' => $this->list));
			break;
        case 'news21Y':
            echo $this->block3(array('list' => $this->list, 'col' => 'col-6 col-md-4'));
            break;
        case 'newsCat21X':
            echo $this->block2(array('list' => $this->list, 'col' => 'col-6 col-xs-4'));
            break;
		case 'productSidebar':
			foreach ($this->list as $value) {
                echo '<li class="product-sidebar-item'.($this->params['parent'] ? '-'.$this->params['parent']:'').'">
                    <a href="'.PUBLIC_PATH.$value['rootSlug'].'/'.$value['slug'].'">
                        <img src="'.PUBLIC_PATH.UPLOAD_IMAGES.date('Y/m',explode('-',$value['thumbnail'])[0]).'/800x800-'.$value['thumbnail'].WEBP_EXT.'" alt="'.$value['name'].'">
                        <div>
                            <div class="title">'.$value['name'].'</div>
                            <div class="price">
                            	'.($value['price'] > 0 && $value['price_market'] > 0 ? '<span class="discount">'.number_format($value['price'],0,0,'.').'₫</span>'.($value['price_discount'] > 0 ? '<span class="market">'.number_format($value['price_market'],0,0,'.').'₫</span>':''):'<span class="discount">Liên hệ</span>').'
                            </div>
                        </div>
                    </a>
                </li>';
            }
			break;
        case 'newsSidebar':
            foreach ($this->list as $value) {
                echo '<div class="col-6 col-md-6 news-sidebar-item'.($this->params['parent'] ? '-'.$this->params['parent']:'').'">
                    <a href="'.PUBLIC_PATH.($value['cat_id'] != 19 ? $value['rootSlug'].'/':'').$value['slug'].'" class="s_block small">
                        <div class="b_thumb ht-ratio--75"><img loading="lazy" width="400" height="300" src="'.PUBLIC_PATH.UPLOAD_IMAGES.date('Y/m',explode('-',$value['thumbnail'])[0]).'/800x600-'.$value['thumbnail'].WEBP_EXT.'" alt="'.$value['name'].'" class="ht-ratio__img"></div>
                        <div class="title">'.$value['name'].'</div>
                    </a>
                </div>';
            }
            break;
        case 'productList11X':
            echo $this->block4(array('list' => $this->list, 'col' => 'col-6 col-sm-4 col-md-3'));
            break;
        case 'productCombo12X':
            echo $this->block5(array('list' => $this->list, 'col' => 'col-6 col-md-3'));
            break;
		default:
			// code...
			break;
	}
?>