<div class="page-content">
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li><a href="<?php echo $this->url('admincp'); ?>"><?php echo $this->translate("Trang chủ"); ?></a><i class="fa fa-circle"></i></li>
            <li><span><?php echo $this->_params['title']; ?></span></li>
        </ul>
        <?php if ($this->identity()->supper) { ?>
            <div class="pull-right">
                <a href="<?php echo $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'codefield','root_id' => $this->_params['root_id'])); ?>" class="btn green pull-right"><i class="fa fa-cogs"></i> Cấu hình dữ liệu</a>
                <a href="<?php echo $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'codevalidate','root_id' => $this->_params['root_id'])); ?>" class="btn green pull-right"><i class="fa fa-cogs"></i> Định nghĩa dữ liệu</a>
                <a href="<?php echo $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'sortfield','root_id' => $this->_params['root_id']), array('query' => array('type' => 'detail'))); ?>" class="btn green pull-right"><i class="fa fa-cogs"></i> Sắp xếp dữ liệu</a>
            </div>
        <?php } ?>
    </div>
    <div class="portlet box blue margin-bottom-0">
        <div class="portlet-title">
            <div class="caption"><?php echo $this->translate("Danh sách"); ?> </div>
            <div class="actions btn-group">
                <?php
                    if ($this->_field['up_date'] && $this->_params['permission']['other']) {
                        echo '<a href="javascript:;" class="btn red" onclick="_HTChange.dateup(\''.$this->linkChange.'\');"><i class="fa fa-refresh "></i> UP</a>';
                    }
                    if ($this->_field['transfer_cate'] && $this->_params['permission']['transfer_cate']) {
                        echo '<a href="javascript:;" class="btn grey-salsa" onclick="_HTChange.cate();"><i class="fa fa-exchange"></i> '.$this->translate("Chuyển danh mục").'</a>';
                    }
                    if ($this->_field['bulk_price'] && $this->_field['price_market'] && $this->_params['permission']['edit']) {
                        echo '<a href="javascript:;" class="btn yellow-mint" onclick="_HTChange.bulkPrice();"><i class="fa fa-money"></i> '.$this->translate("Cập nhật giá").'</a>';
                    }
                    if ($this->_field['add'] || $this->_field['delete']) {
                        if ($this->_field['add'] && $this->_params['permission']['add']) {
                            echo '<a href="'.$this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'field','root_id' => $this->_params['root_id'])).'" class="btn yellow"><i class="fa fa-plus-square-o"></i> '.$this->translate("Thêm").'</a>';
                        }
                        if($this->_field['delete']) {
                            if ($this->_params['permission']['delete'] || $this->_params['permission']['d-status']) {
                                echo '<a href="javascript:;" class="btn red" onclick="_HTDelete.rows(\''.$this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'delete')).'\',\'/root_id='.$this->_params['root_id'].'\');"><i class="fa fa-trash-o"></i> '.$this->translate("Xóa nhiều").'</a>';
                            }
                        }
                    }
                ?>
            </div>
        </div>
        <div class="portlet-body">
            <?php if ($this->_field['cat_id']) { ?>
                <div class="ht-filter">
                    <form id="form-filter" action="" method="post" accept-charset="utf-8">
                        <div class="ht-filter__category">
                            <div class="input-group input-group-sm select2-bootstrap-prepend">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button" data-select2-open="ht-open-boxCate"><?php echo $this->translate("Danh mục"); ?></button>
                                </span>
                                <select name="cat_id" id="ht-open-boxCate" class="form-control select2" onchange="_HTHelper.submit(this);">
                                    <option value="0"><?php echo $this->translate("Tất cả"); ?></option>
                                    <?php foreach ($this->filter as $value) { ?>
                                        <option value="<?php echo $value['id']; ?>" <?php echo ($value['id'] == $this->query['cat_id']) ? 'selected' : ''; ?> class="level<?php echo $value['level']; ?>"><?php echo $value['name']; ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>
                    </form>
                </div>
            <?php } ?>
            <table id="datatable-product" class="table table-striped table-bordered table-hover table-checkable action-column<?php echo ($this->_field['colvis'] ? ' colvis-column' : '').(($this->_field['excel'] && $this->_params['permission']['excel']) ? ' excel-column' : ''); ?>">
                <?php
                    $columns = array();
                    foreach ($this->columns as $column) {
                        if ($column['colvis'] != true) {
                            $columns[] = array(
                                'name' => $column['name'],
                                'data' => $column['data'],
                                'title' => $column['title'],
                                'class' => $column['class'] ?? 'min-width-100',
                                'orderable' => $column['orderable'] ?? false,
                                'searchable' => $column['searchable'] ?? false,
                            );
                        }
                    }
                ?>
            </table>
        </div>
    </div>
    <?php if ($this->_field['cat_id']) { ?>
        <div id="change-cate" class="modal fade" tabindex="-1" role="basic" data-backdrop="static" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header"><h4 class="modal-title text-center text-uppercase"><?php echo $this->translate("Chuyển danh mục"); ?></h4></div>
                    <div class="modal-body">
                        <div class="input-group select2-bootstrap-prepend">
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="button" data-select2-open="ht-open-changeCate"><?php echo $this->translate("Danh mục"); ?></button>
                            </span>
                            <select name="cat_id" id="ht-open-changeCate" class="form-control select2">
                                <option></option>
                                <?php foreach ($this->filter as $value) { ?>
                                    <option value="<?php echo $value['id']; ?>" class="level<?php echo $value['level']; ?>"><?php echo $value['name']; ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <div class="text-center">
                            <button type="button" class="btn salsa" onclick="_HTChange.cate('<?php echo $this->linkChange; ?>');"><i class="fa fa-exchange"></i> <?php echo $this->translate("Chuyển danh mục"); ?></button>
                            <button type="button" class="btn red" data-dismiss="modal"><i class="fa fa-ban"></i> <?php echo $this->translate("Hủy"); ?></button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php } ?>
    <?php if ($this->_field['bulk_price'] && $this->_field['price_market']) { ?>
        <div id="change-price" class="modal modal-change-price fade" tabindex="-1" role="basic" data-backdrop="static" aria-hidden="true">
            <form id="form-bulk-price" action="" method="POST" enctype="multipart/form-data">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header"><h4 class="modal-title text-center text-uppercase"><?php echo $this->translate("Cập nhật giá"); ?></h4></div>
                        <div class="modal-body">
                            <div class="form-group">
                                <span>Hình thức:</span>
                                <label class="mt-radio mt-radio-outline"><input type="radio" name="type" value="1" checked><span></span>Tăng</label>
                                <label class="mt-radio mt-radio-outline"><input type="radio" name="type" value="-1"><span></span>Giảm</label>
                            </div>
                            <div class="form-group <?php echo $this->_field['price_discount'] ? '' : 'only-price-market'; ?>">
                                <span>Thay đổi:</span>
                                <label class="mt-checkbox mt-checkbox-outline"><input type="checkbox" name="price[]" value="price_market" <?php echo $this->_field['price_discount'] ? '' : 'checked' ?> /><span></span><?php echo $this->_field['price_market'] ?></label>
                                <?php if ($this->_field['price_discount']) { ?>
                                    <label class="mt-checkbox mt-checkbox-outline"><input type="checkbox" name="price[]" value="price_discount" /><span></span><?php echo $this->_field['price_discount'] ?></label>
                                <?php } ?>
                            </div>
                            <div class="form-group" style="display: flex">
                                <span id="number-apply">Tăng theo:</span>
                                <div>
                                    <label class="mt-radio mt-radio-outline"><input type="radio" name="ratio" value="1" checked><span></span>Tỷ lệ (%)</label>
                                    <label class="mt-radio mt-radio-outline"><input type="radio" name="ratio" value="-1"><span></span>Số tiền ($)</label>
                                    <input type="text" class="form-control" name="number" ht-trigger="number" data-unit="<?php echo $this->_field['unit'] ?>" value="" style="margin-top: 5px; width: 185px"; />
                                </div>
                            </div>
                            <div id="change-price-error-negative" style="display: none">
                                <p style="font-style: italic;">*Vui lòng kiểm tra lại sản phẩm sau vì <?php echo $this->_field['price_market'].' hoặc '.$this->_field['price_discount'] ?> sau cập nhật nhỏ hơn 0:</p>
                                <div id="change-price-negative-products"></div>
                            </div>
                            <div id="change-price-error-compare" style="display: none">
                                <p style="font-style: italic;">*Vui lòng kiểm tra lại sản phẩm sau vì <?php echo $this->_field['price_market'] ?> sau cập nhật nhỏ hơn hoặc bằng <?php echo $this->_field['price_discount'] ?>:</p>
                                <div id="change-price-compare-products"></div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <div class="text-center">
                                <button type="submit" class="btn salsa"><i class="fa fa fa-money"></i> <?php echo $this->translate("Cập nhật"); ?></button>
                                <button type="button" class="btn red" data-dismiss="modal"><i class="fa fa-ban"></i> <?php echo $this->translate("Hủy"); ?></button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <script>
            $(document).ready(function() {
                var rules = {
                    type: {required: true},
                    'price[]': {required: true},
                    ratio: {required: true},
                    number: {
                        required: true,
                        max: 100,
                    },
                };

                FormValidation.submit('#form-bulk-price', {rules: rules});

                $('input[name=ratio]').click(function(event) {
                    rules.number = {
                        required: true
                    };
                    if ($(this).val() == 1) {
                        rules.number.max = 100;
                    }
                    $('#form-bulk-price').validate().resetForm();
                    $('#form-bulk-price').validate().settings.rules = rules;
                });

                $('input[name=type]').click(function(event) {
                    $('#number-apply').text($(this).parent().text() + ' theo:');
                });

                $('#form-bulk-price').submit(function(event) {
                    if ($('#form-bulk-price').validate().errorList.length === 0) {
                        var url = "<?php echo $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'bulkPrice')); ?>" + "/id=" + _HTCheck.checkall() + "/root_id=<?php echo $this->_params['root_id']; ?>";
                        var type = $('#form-bulk-price input[name=type]:checked').val();
                        var ratio = $('#form-bulk-price input[name=ratio]:checked').val();
                        var number = $('#form-bulk-price input[name=number]').val();
                        var price = [];
                        $('#form-bulk-price input[name="price[]"]').each(function(index, el) {
                           if (el.checked) {
                            price.push(el.value);
                           }
                        });
                        $.ajax({
                            url: url,
                            type: 'post',
                            data: {
                                type: type,
                                price: price,
                                ratio: ratio,
                                number: number,
                            },
                            beforeSend: function() {
                                $('#form-bulk-price .modal-content').append('<span class="looploading"><span></span><span></span><span></span></span>');
                            }
                        })
                        .done(function(data) {
                            var error = $.parseJSON(data);
                            $('.looploading').remove();
                            $('#change-price-error-negative').hide();
                            $('#change-price-negative-products').empty();
                            $('#change-price-error-compare').hide();
                            $('#change-price-compare-products').empty();

                            if (error.negative.length > 0) {
                                $('#change-price-error-negative').show();
                                for (var i = 0; i < error.negative.length; i++) {
                                    $('#change-price-negative-products').append('<p>- '+error.negative[i].name+'</p>');
                                }
                            }

                            if (error.compare.length > 0) {
                                $('#change-price-error-compare').show();
                                for (var j = 0; j < error.compare.length; j++) {
                                    $('#change-price-compare-products').append('<p>- '+error.compare[j].name+'</p>');
                                }
                            }

                            if (error.negative.length == 0 && error.compare.length == 0) {
                                location.reload();
                            }
                        });
                    }

                    return false;
                });
            });
        </script>
    <?php } ?>
</div>
<script>
    $(document).ready(function() {
        var tableId = '#datatable-product';

        TableDatatables.init({
            'tableId': tableId,
            'processing': false,
            'serverSide': true,
            'select': false,
            'columns': $.parseJSON('<?php echo json_encode($columns); ?>'),
            'customize': {
                colvis: '<?php echo $this->_field['colvis'] ? $this->url('admincp', array('controller' => $this->_params['__CONTROLLER__'],'action' => 'sortfield','root_id' => $this->_params['root_id']), array('query' => array('type' => 'list'))) : ''; ?>',
                excel: '<?php echo $this->_field['excel'] && $this->_params['permission']['excel'] ? true : false; ?>',
            },
            'ajax': {
                'type': 'POST',
                'url': "<?php echo $this->url('admincp',array('controller' => $this->_params['__CONTROLLER__'],'action' => 'list', 'root_id' => $this->_params['root_id'])).($_SERVER['QUERY_STRING'] ? '?'.$_SERVER['QUERY_STRING'] : ''); ?>",
                // 'data': function(d) {
                //     console.log(d);
                // },
                // dataFilter: function(reps) {
                //     console.log($.parseJSON(reps));
                //     return reps;
                // },
            },
            drawCallback: function( settings ) {
                FormEditable.price('editable-price', {unit: '<?php echo $this->_field['unit']; ?>'});
            }
        });

        $('body').on('click', '.editable-click', function() {
            if ($(this).hasClass('editable-open')) {
                $("#datatable-product .editable-open").not(this).click();
                var tagARect = this.getBoundingClientRect();
                var $this = $(this);
                setTimeout(function() {
                    var domRect = $this.siblings('.popover')[0].getBoundingClientRect();
                    $this.siblings('.popover').removeClass('top');
                    $this.siblings('.popover').addClass('bottom');
                    $this.siblings('.popover').css({
                        position: 'fixed',
                        top: (domRect.top  - (tagARect.height/2)) + 'px',
                        left: domRect.left + 'px',
                    });
                }, 100);
            }
        });

        document.addEventListener("scroll", function(){
            $("#datatable-product .editable-open").click();
        });
    });
</script>